### ISSUE TITLE
[BUG] Error on download

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#1053]
![image](https://user-images.githubusercontent.com/1136496/120025544-1c6f1e80-bff1-11eb-94e4-76c0d11c4c27.png)

![image](https://user-images.githubusercontent.com/1136496/120026426-5b51a400-bff2-11eb-90a1-ba16a81cde92.png)

**Comment by akasolace** [comment]
same bug as reported by @poteus  #1038  (no idea how I ended up with this wrong entry during data download ....

**Comment by akasolace** [comment]
@wsbrenk I can't ind any reference to that game. I never faced that opponent.
The match report mentions some of my newly acquired players. It seems to me this is  a bug on CHPP site ....

**Comment by akasolace** [comment]
I reported the bug on HT forums

**Comment by akasolace** [comment]
@wsbrenk also I noticed that downloading new data cause download of lineups for all game in matkurzinfo table,  should ze not li,it this to most recent game or even do lazy doznload of lineup ?

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/120068632-ec239080-c081-11eb-9134-92279cd97463.png)

this tournament matches are no longer given by match archive. this gives the errors.

**Comment by wsbrenk** [comment]
@akasolace i haven't played tournament matches for quite a long time. Could you please check if you find out how long those matches are kept in ht match archive? 

my first guess is, that i don't reload those matches if they are older than one year.

**Comment by wsbrenk** [comment]
> also I noticed that downloading new data cause download of lineups for all game in matkurzinfo table, should ze not li,it this to most recent game or even do lazy doznload of lineup ?

are you sure, if really ALL matches details/highlights were reloaded or not only a maximum of 10 each time you start your HO?

**Comment by akasolace** [comment]
Just to understand the issue ... you are saying that tournament games are simply dropped from ht ? In that case I still don't understand why March details shows wrong match date ....

**Comment by wsbrenk** [comment]
my assumption is probably wrong. I have just found tournament games from 2016 in the archive. Maybe matches were stored as htoIntegrated matches which weren't htointegrated, wrong match type or anything like this.

most of the changes of my pr should help to store with correct sourceSystem. the isObsolet method should be modified - if we know what kind of wrong matches were in the database.

**Comment by akasolace** [comment]
the fake entry in my db, says the game was played the 2021-05-23 17:26:52 and I got a match report

**Comment by akasolace** [comment]
it really seems a bug from CHPP

**Comment by akasolace** [comment]
![image](https://user-images.githubusercontent.com/1136496/120081373-9ff64180-c0bd-11eb-99da-bdab9d47d5b5.png)

![image](https://user-images.githubusercontent.com/1136496/120081379-a8e71300-c0bd-11eb-99be-b9970d2c52b2.png)

here it is:
![image](https://user-images.githubusercontent.com/1136496/120081407-cd42ef80-c0bd-11eb-9f35-901eeabb8177.png)

**Comment by akasolace** [comment]
and it seems that all info of the game are in the db:
![image](https://user-images.githubusercontent.com/1136496/120081437-fb283400-c0bd-11eb-8ba5-baeb788f53c5.png)

![image](https://user-images.githubusercontent.com/1136496/120081443-04b19c00-c0be-11eb-83be-cdaff606376e.png)



HO! shoud not try to download those data again ... something wrong here also on HO! side ...

**Comment by wsbrenk** [comment]
@akasolace could it be, that hasUnsureWeatherForecast is not working as expected on those games, causing the ONlineWorker to download those matches again?
should return false on matches that are finished.

**Comment by akasolace** [comment]
Might be
When I got time I will investigate

**Comment by wsbrenk** [comment]
Thesis: the bugs that are fixed in my current pr (download with wrong source system) have led in recent weeks to the fact that matches that are actually HtoIntegrated have been loaded as a hattrick source system (totally outdated game reports). We have saved these and now they lead to the observed errors.

**Comment by wsbrenk** [comment]
@akasolace another point: even if isObsolet is not in line with the hattrick rules, I think we could introduce it as a HO rule. who might be interested in hto matches that are older than one year?!

**Comment by wsbrenk** [comment]
Sorry - but this change crashed my database:

 [Error]   JDBCAdapter: JDBCAdapter.executeQuery : java.sql.SQLSyntaxErrorException: column is referenced in: PUBLIC.PK_MATCHID in statement [ALTER TABLE MATCHDETAILS DROP COLUMN SourceSystem]
Statement: ALTER TABLE MATCHDETAILS DROP COLUMN SourceSystem
java.sql.SQLSyntaxErrorException: column is referenced in: PUBLIC.PK_MATCHID in statement [ALTER TABLE MATCHDETAILS DROP COLUMN SourceSystem]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.executeQuery(Unknown Source)
	at core.db.JDBCAdapter.executeQuery(JDBCAdapter.java:58)
	at core.db.AbstractTable.tryDeleteColumn(AbstractTable.java:179)
	at core.db.DBUpdater.updateDBv500(DBUpdater.java:294)
	at core.db.DBUpdater.updateDB(DBUpdater.java:60)
	at core.db.DBManager.instance(DBManager.java:213)
	at core.HO.main(HO.java:149)
Caused by: org.hsqldb.HsqlException: column is referenced in: PUBLIC.PK_MATCHID
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.TableWorks.dropColumn(Unknown Source)
	at org.hsqldb.StatementSchema.getResult(Unknown Source)
	at org.hsqldb.StatementSchema.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 8 more

 [Error]   JDBCAdapter: JDBCAdapter.executeQuery : java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10151 table: MATCHLINEUP column: MATCHTYP
Statement: UPDATE MATCHLINEUP t1 SET MATCHTYP = (SELECT MK.MATCHTYP FROM MATCHESKURZINFO MK WHERE t1.MATCHID = MK.MATCHID)
java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10151 table: MATCHLINEUP column: MATCHTYP
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.executeQuery(Unknown Source)
	at core.db.JDBCAdapter.executeQuery(JDBCAdapter.java:58)
	at core.db.DBUpdater.updateDBv500(DBUpdater.java:314)
	at core.db.DBUpdater.updateDB(DBUpdater.java:60)
	at core.db.DBManager.instance(DBManager.java:213)
	at core.HO.main(HO.java:149)
Caused by: org.hsqldb.HsqlException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10151 table: MATCHLINEUP column: MATCHTYP
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Table.enforceRowConstraints(Unknown Source)
	at org.hsqldb.Table.generateAndCheckData(Unknown Source)
	at org.hsqldb.Table.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementDML.update(Unknown Source)
	at org.hsqldb.StatementDML.executeUpdateStatement(Unknown Source)
	at org.hsqldb.StatementDML.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 7 more

 [Error]   JDBCAdapter: JDBCAdapter.executeQuery : java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_PK_11389 table: MATCHDETAILS column: MATCHTYP in statement [ALTER TABLE MATCHDETAILS ADD PRIMARY KEY (MATCHID, MATCHTYP)]
Statement: ALTER TABLE MATCHDETAILS ADD PRIMARY KEY (MATCHID, MATCHTYP)
java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_PK_11389 table: MATCHDETAILS column: MATCHTYP in statement [ALTER TABLE MATCHDETAILS ADD PRIMARY KEY (MATCHID, MATCHTYP)]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.executeQuery(Unknown Source)
	at core.db.JDBCAdapter.executeQuery(JDBCAdapter.java:58)
	at core.db.DBUpdater.updateDBv500(DBUpdater.java:321)
	at core.db.DBUpdater.updateDB(DBUpdater.java:60)
	at core.db.DBManager.instance(DBManager.java:213)
	at core.HO.main(HO.java:149)
Caused by: org.hsqldb.HsqlException: integrity constraint violation: NOT NULL check constraint; SYS_PK_11389 table: MATCHDETAILS column: MATCHTYP
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Table.enforceRowConstraints(Unknown Source)
	at org.hsqldb.persist.RowStoreAVL.moveData(Unknown Source)
	at org.hsqldb.TableWorks.moveData(Unknown Source)
	at org.hsqldb.TableWorks.addPrimaryKey(Unknown Source)
	at org.hsqldb.StatementSchema.getResult(Unknown Source)
	at org.hsqldb.StatementSchema.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 7 more

 [Info]    HOVerwaltung: language used for interface is: Deutsch
 [Info]    HOMainFrame: This is HO! version 0.0 DEV (r0), have fun!
 [Info]    HOMainFrame: Operating system found: Windows 10 on amd64 (10.0)
 [Info]    HOMainFrame: Using java: 15.0.2 (AdoptOpenJDK)
 [Error]   ExceptionHandler: java.lang.StackOverflowError
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)
 [Error]   ExceptionHandler: module.youth.YouthTraining.getMatchLineup(YouthTraining.java:109)

**Comment by wsbrenk** [comment]
youth matches have no entry in MatchKurzInfo

youthtraining.matchid 
 - matchdetails.matchid, matchdetails.sourcesystem=1
 - matchlineup.matchid, matchlineup.sourcesystem=1 (matchlineup.matchtyp=100, 106)
 - matchhighlights.matchid, matchhighlights.sourcesystem=1
 - matchlineupteam.matchid, matchlineupteam.sourcesystem=1
 - matchlineupplayer.matchid, matchlineupplayer.sourcesystem=1
 - matchsubstitution.matchid, matchsubstitution.sourcesystem=1

**Comment by akasolace** [comment]
Actually I realized yesterday it requires an even bigger refactoring. There are plenty of errors because of current implementation. I will match MatchType 1 to 1 with HT.
I will add function getMatchIcon directly into match object. I will be careful with youthMarch treatment.

**Comment by wsbrenk** [comment]
@akasolace the missing matches are back again: Great job!

![image](https://user-images.githubusercontent.com/11821502/120933338-0270c280-c6fa-11eb-9b2d-f23fb0eb2885.png)

**Comment by akasolace** [comment]
@wsbrenk not sure it is all fixed so I leave the ticket open for the time being .. but we should be getting closer to first beta ...

**Comment by akasolace** [comment]
duplicate of #1062
