### ISSUE TITLE
[BUG]NPE in Player.calcSubskills

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1094]
HO-dev5.0.3650

java.lang.NullPointerException: Cannot invoke "core.training.TrainingPerWeek.skillDropDayIsBetween(java.time.Instant, java.time.Instant)" because the return value of "core.training.TrainingManager.getNextWeekTraining()" is null
	at core.model.player.Player.calcSubskills(Player.java:2426)
	at core.model.HOModel.calcSubskills(HOModel.java:513)
	at core.net.DownloadDialog.startDownload(DownloadDialog.java:360)
	at core.net.DownloadDialog.actionPerformed(DownloadDialog.java:92)

**Comment by wsbrenk** [comment]
same as #1082

**Comment by wsbrenk** [comment]
fix is not released (with ho 3650)

merge was done after release of 3650
