### ISSUE TITLE
[BUG]HO3 can not update to current beta HO5

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1224]
feedback from HT forum:

New, clear HO 5.0 is working fine, but when I try to update my old 3.0 version an error appears: "java.io.FileNotFoundException: https://akasolace.github.io/HO/release_notes(stable).html" and nothing happens. I tried dev, beta and stable release channel.

here is the log file:
[Error] core.net.MyConnector: Download Error
HTTP Response Code: 404
java.lang.RuntimeException: Download Error
HTTP Response Code: 404
at core.net.MyConnector.getNonCHPPWebFile(MyConnector.java:735)
at core.net.MyConnector.getFileFromWeb(MyConnector.java:638)
at tool.updater.UpdateHelper.download(UpdateHelper.java:55)
at tool.updater.UpdateController.updateHO(UpdateController.java:161)
at tool.updater.UpdateController.updateHO(UpdateController.java:153)
at tool.updater.UpdateController.check4update(UpdateController.java:125)
at core.gui.HOMainFrame.actionPerformed(HOMainFrame.java:408)
at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at javax.swing.AbstractButton.doClick(Unknown Source)
at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Window.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by wsbrenk** [comment]
22:21:18 [Info] core.gui.HOMainFrame: This is HO! version 3.0, have fun!
22:21:18 [Info] core.gui.HOMainFrame: Operating system found: Windows 10 on x86 (10.0)
22:21:18 [Info] core.gui.HOMainFrame: Using java: 1.8.0_281 (Oracle Corporation)
22:21:39 [Error] core.net.MyConnector: Download Error
HTTP Response Code: 404
java.lang.RuntimeException: Download Error
HTTP Response Code: 404
at core.net.MyConnector.getNonCHPPWebFile(MyConnector.java:735)
at core.net.MyConnector.getFileFromWeb(MyConnector.java:638)
at tool.updater.UpdateHelper.download(UpdateHelper.java:55)
at tool.updater.UpdateController.updateHO(UpdateController.java:161)
at tool.updater.UpdateController.updateHO(UpdateController.java:153)
at tool.updater.UpdateController.check4update(UpdateController.java:125)
at core.gui.HOMainFrame.actionPerformed(HOMainFrame.java:408)
at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at javax.swing.AbstractButton.doClick(Unknown Source)
at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Window.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by wsbrenk** [comment]
public static String get_HO_zip_download_url(String full_version, double version, String versionType) {
        if (versionType == "DEV") {
            return "https://github.com/akasolace/HO/releases/download/dev/HO_" + full_version + ".zip";
        } else {
            String ver = Double.toString(version);
            return "https://github.com/akasolace/HO/releases/download/" + ver + "/HO_" + full_version + ".zip";
        }
    }

**Comment by wsbrenk** [comment]
left to do:

* create tag 5.0 containing HO_5.*.zip
* update HO/docs/latestbeta.html with correct version value
