### ISSUE TITLE
[BUG]NPE on HO start

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1237]
not all players are displayed

01:08:41 [Error]   core.db.JDBCAdapter: JDBCAdapter.executeQuery : java.sql.SQLException: java.lang.NullPointerException: Cannot read field "nNext" because "<local2>" is null
Statement: SELECT * FROM BASICS WHERE Datum >='1970-01-01 01:00:00.0' ORDER BY Datum DESC
java.sql.SQLException: java.lang.NullPointerException: Cannot read field "nNext" because "<local2>" is null
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.executeQuery(Unknown Source)
	at core.db.JDBCAdapter.executeQuery(JDBCAdapter.java:58)
	at core.db.BasicsTable.getCBItemHRFListe(BasicsTable.java:137)
	at core.db.DBManager.getCBItemHRFListe(DBManager.java:793)
	at module.playerOverview.SpielerTrainingsVergleichsPanel.loadHRFListe(SpielerTrainingsVergleichsPanel.java:170)
	at module.playerOverview.SpielerTrainingsVergleichsPanel.<init>(SpielerTrainingsVergleichsPanel.java:55)
	at module.playerOverview.SpielerUebersichtsPanel.initSpielerHistory(SpielerUebersichtsPanel.java:148)
	at module.playerOverview.SpielerUebersichtsPanel.initComponents(SpielerUebersichtsPanel.java:107)
	at module.playerOverview.SpielerUebersichtsPanel.<init>(SpielerUebersichtsPanel.java:32)
	at module.playerOverview.PlayerOverviewModule.createTabPanel(PlayerOverviewModule.java:30)
	at core.gui.comp.tabbedPane.HOTabbedPane.showTab(HOTabbedPane.java:38)
	at core.gui.HOMainFrame.initComponents(HOMainFrame.java:429)
	at core.gui.HOMainFrame.<init>(HOMainFrame.java:151)
	at core.gui.HOMainFrame.instance(HOMainFrame.java:216)
	at core.HO.lambda$main$2(HO.java:209)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.hsqldb.HsqlException: java.lang.NullPointerException: Cannot read field "nNext" because "<local2>" is null
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.result.Result.newErrorResult(Unknown Source)
	at org.hsqldb.result.Result.newErrorResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 29 more
Caused by: java.lang.NullPointerException: Cannot read field "nNext" because "<local2>" is null
	at org.hsqldb.RowAVL.getNode(Unknown Source)
	at org.hsqldb.index.NodeAVLDisk.findNode(Unknown Source)
	at org.hsqldb.index.NodeAVLDisk.getRight(Unknown Source)
	at org.hsqldb.index.IndexAVL.findNode(Unknown Source)
	at org.hsqldb.index.IndexAVL.findFirstRow(Unknown Source)
	at org.hsqldb.RangeVariable$RangeIteratorMain.getFirstRow(Unknown Source)
	at org.hsqldb.RangeVariable$RangeIteratorMain.initialiseIterator(Unknown Source)
	at org.hsqldb.RangeVariable$RangeIteratorMain.next(Unknown Source)
	at org.hsqldb.QuerySpecification.buildResult(Unknown Source)
	at org.hsqldb.QuerySpecification.getSingleResult(Unknown Source)
	at org.hsqldb.QuerySpecification.getResult(Unknown Source)
	at org.hsqldb.StatementQuery.getResult(Unknown Source)
	... 33 more

**Comment by wsbrenk** [comment]
reason was a corrupt database - fixed it by restoring an old one.
