### ISSUE TITLE
[BUG]HO5 doesn't start

### ISSUE THREAD

**Issue by Volker-brdb** [akasolace/HO#1284]
**Describe the bug**
HO5 does not start

**To Reproduce**
Download HOSetup-5.0.3836.2-JRE.exe
Install HOSetup-5.0.3836.2-JRE.exe
Start HO.exe

**Screenshots**
java.lang.UnsupportedClassVersionError: core/HOLauncher has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 58.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:642)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:80)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

**Platform information:**
 - OS: Windows

**Additional context**

**Comment by Volker-brdb** [comment]
tried version without JRE HOSetup-5.0.3836.2 ...same result

**Comment by Volker-brdb** [comment]
ok, my fault :-) issue solved
