### ISSUE TITLE
[BUG] Illegal Argument in player overview

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1380]
java.lang.IllegalArgumentException: The provided string is not recognized as a valid DateTime: 
	at core.util.HTDatetime.cleanDateTimeString(HTDatetime.java:160)
	at core.util.HTDatetime.<init>(HTDatetime.java:48)
	at module.playerOverview.PlayerDetailsPanel.setLabels(PlayerDetailsPanel.java:313)
	at module.playerOverview.PlayerDetailsPanel.setPlayer(PlayerDetailsPanel.java:130)
	at module.playerOverview.SpielerUebersichtsPanel.setPlayer(SpielerUebersichtsPanel.java:50)
	at core.gui.HOMainFrame.setActualSpieler(HOMainFrame.java:234)
	at module.lineup.LineupPanel$1.synchronizeSelection(LineupPanel.java:214)
	at module.lineup.LineupPanel$1.valueChanged(LineupPanel.java:191)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:448)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:458)
	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:502)
	at java.desktop/javax.swing.JTable.setRowSelectionInterval(JTable.java:2230)
	at module.lineup.LineupPanel$1.synchronizeSelection(LineupPanel.java:210)
	at module.lineup.LineupPanel$1.valueChanged(LineupPanel.java:193)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:448)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:458)
	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:502)
	at java.desktop/javax.swing.JTable.setRowSelectionInterval(JTable.java:2230)
	at module.playerOverview.LineupPlayersTableNameColumn.setPlayer(LineupPlayersTableNameColumn.java:56)
	at module.lineup.LineupPanel.setPlayer(LineupPanel.java:49)
	at core.gui.HOMainFrame.setActualSpieler(HOMainFrame.java:233)
	at module.playerOverview.SpielerUebersichtsPanel.lambda$addTableSelectionListeners$2(SpielerUebersichtsPanel.java:245)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:448)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:458)
	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:502)
	at java.desktop/javax.swing.JTable.setRowSelectionInterval(JTable.java:2230)
	at module.playerOverview.SpielerUebersichtsPanel.selectRow(SpielerUebersichtsPanel.java:220)
	at module.playerOverview.SpielerUebersichtsPanel.lambda$addTableSelectionListeners$1(SpielerUebersichtsPanel.java:233)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:448)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:458)
	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:502)
	at java.desktop/javax.swing.JTable.changeSelectionModel(JTable.java:2435)
	at java.desktop/javax.swing.JTable.changeSelection(JTable.java:2504)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(BasicTableUI.java:1154)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(BasicTableUI.java:1077)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)

**Comment by wsbrenk** [comment]
only happens before the very first download with current HO dev

**Comment by wsbrenk** [comment]
@akasolace it is the arrival date, that is missing as long as no download was made.

**Comment by akasolace** [comment]
Ok indeed something I introduced lately while working on new player analysis ...
I will fix it asap but I might not have a lot of time this week.

**Comment by wsbrenk** [comment]
similar if i create a temp player in skilltester:

java.lang.NullPointerException: Cannot invoke "String.length()" because "sDateTime" is null
	at core.util.HTDatetime.cleanDateTimeString(HTDatetime.java:157)
	at core.util.HTDatetime.<init>(HTDatetime.java:48)
	at module.playerOverview.PlayerDetailsPanel.setLabels(PlayerDetailsPanel.java:313)
	at module.playerOverview.PlayerDetailsPanel.setPlayer(PlayerDetailsPanel.java:130)
	at module.playerOverview.SpielerUebersichtsPanel.setPlayer(SpielerUebersichtsPanel.java:50)
	at core.gui.HOMainFrame.setActualSpieler(HOMainFrame.java:234)
	at module.playerOverview.SpielerUebersichtsPanel.lambda$addTableSelectionListeners$2(SpielerUebersichtsPanel.java:245)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:448)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:458)
	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:502)
	at java.desktop/javax.swing.JTable.changeSelectionModel(JTable.java:2435)

**Comment by wsbrenk** [comment]
as the many different DateTime treatments in HO confuse me more and more, I have built another new class

HODateTime is a simplification of HTDateTime. I would like to replace all time treatments with this approach.
