### ISSUE TITLE
NullPointerException: core.model.XtraData.getNextTrainingDate()" is null

### ISSUE THREAD

**Issue by Michelinho96** [akasolace/HO#1394]
java.lang.NullPointerException: Cannot invoke "java.sql.Timestamp.getTime()" because the return value of "core.model.XtraData.getNextTrainingDate()" is null
	at core.util.HTCalendarFactory.createTrainingCalendar(HTCalendarFactory.java:97)
	at core.util.HTCalendarFactory.createTrainingCalendar(HTCalendarFactory.java:116)
	at core.util.HTCalendarFactory.getHTSeason(HTCalendarFactory.java:125)
	at core.gui.model.MatchOrdersCBItem.createComponent(MatchOrdersCBItem.java:54)
	at core.gui.model.MatchOrdersCBItem.getComponent(MatchOrdersCBItem.java:36)
	at core.gui.model.MatchOrdersCBItem.getListCellRendererComponent(MatchOrdersCBItem.java:89)
	at core.gui.model.MatchOrdersRenderer.getListCellRendererComponent(MatchOrdersRenderer.java:15)
	at core.gui.model.MatchOrdersRenderer.getListCellRendererComponent(MatchOrdersRenderer.java:10)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1439)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1389)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2785)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:199)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:246)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:443)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:453)
	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:497)
	at java.desktop/javax.swing.JList.setSelectedIndex(JList.java:2205)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup.setListSelection(BasicComboPopup.java:1234)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup$Handler.itemStateChanged(BasicComboPopup.java:1058)
	at java.desktop/javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1227)
	at java.desktop/javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1288)
	at java.desktop/javax.swing.JComboBox.contentsChanged(JComboBox.java:1335)
	at java.desktop/javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:123)
	at java.desktop/javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:94)
	at java.desktop/javax.swing.DefaultComboBoxModel.addElement(DefaultComboBoxModel.java:132)
	at java.desktop/javax.swing.JComboBox.addItem(JComboBox.java:716)
	at module.lineup.lineup.MatchAndLineupSelectionPanel.update_jcbUpcomingGames(MatchAndLineupSelectionPanel.java:382)
	at module.lineup.lineup.MatchAndLineupSelectionPanel.updateComponents(MatchAndLineupSelectionPanel.java:166)
	at module.lineup.lineup.MatchAndLineupSelectionPanel.initComponents(MatchAndLineupSelectionPanel.java:153)
	at module.lineup.lineup.MatchAndLineupSelectionPanel.<init>(MatchAndLineupSelectionPanel.java:61)
	at module.lineup.lineup.LineupPositionsPanel.initComponents(LineupPositionsPanel.java:241)
	at module.lineup.lineup.LineupPositionsPanel.<init>(LineupPositionsPanel.java:106)
	at module.lineup.LineupPanel.initComponents(LineupPanel.java:107)
	at module.lineup.LineupPanel.<init>(LineupPanel.java:38)
	at module.lineup.LineupMasterView.initComponents(LineupMasterView.java:50)
	at module.lineup.LineupMasterView.<init>(LineupMasterView.java:38)
	at module.lineup.LineupModule.createTabPanel(LineupModule.java:29)
	at core.gui.comp.tabbedPane.HOTabbedPane.showTab(HOTabbedPane.java:38)
	at core.gui.HOMainFrame.initComponents(HOMainFrame.java:429)
	at core.gui.HOMainFrame.<init>(HOMainFrame.java:151)
	at core.gui.HOMainFrame.instance(HOMainFrame.java:216)
	at core.HO.lambda$main$2(HO.java:209)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by wsbrenk** [comment]
not sure - but i think this is fixed

**Comment by wsbrenk** [comment]
this part was refactored by #1389
