### ISSUE TITLE
[BUG] - OutOfMemoryError

### ISSUE THREAD

**Issue by padr19** [akasolace/HO#1395]
**Describe the bug**
HO doesnt start, ends up with this error.

**To Reproduce**
1. Pure install
2. Import a lot of hrf files

**Screenshots**
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.StringUTF16.newBytesFor(StringUTF16.java:53)
	at java.base/java.lang.AbstractStringBuilder.inflate(AbstractStringBuilder.java:272)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:802)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:240)
	at core.db.DBManager.deleteEscapeSequences(DBManager.java:2583)
	at core.db.StaffTable.getStaffByHrfId(StaffTable.java:52)
	at core.db.DBManager.getStaffByHrfId(DBManager.java:1447)
	at core.model.HOModel.<init>(HOModel.java:98)
	at core.model.HOVerwaltung.loadModel(HOVerwaltung.java:206)
	at core.model.HOVerwaltung.loadLatestHoModel(HOVerwaltung.java:122)
	at core.HO.main(HO.java:183)
	at core.HOLauncher.main(HOLauncher.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

**Platform information:**
 - OS: Windows
 - Version [5.2.3945.2]

**Comment by masterpatje** [comment]
I downloaded a lot of files in v6.0.261 and previous versions of 6.0. A lot of .hrf files even up to 2012 (!) and all worked fine. So I would advise to use the new 6.0 version and close this issue. 

The issue is related to v5.2 so not relevant to the v6.0 versions.

**Comment by padr19** [comment]
You are right, version 6 works very well. Thank you.
