### ISSUE TITLE
Database Corruption?

### ISSUE THREAD

**Issue by Crip1** [akasolace/HO#1399]
This morning, I tried to open HO 3.0 on Windows for my team.   It opened, then got an error message connection to www.hattrick.org could not be established: Error fetching matchlineup.

Once I proceed with download, I received a bunch of other error messages, and now the .db seems to be corrupt.    When I shut down and try to re-launch HO, it gets hung up in the loading process, and I end up with a HO window showing status, but no progress, so I suspect that .db is now corrupt.

Later when trying for 2nd team, same sequence of events occurred.

**Comment by manguz** [comment]
It happens with 4.1 and latest 6.0 but I don't see DB corruption I think.
HO restart ok with the changes applied, data seems still downloaded

Crip1, maybe your DB is locked after shutdown in that old version

**Comment by Crip1** [comment]
I see a database.lck file, but I am unable to delete it, am told that it is currently in use by Java.

 

"C:\Users\garth\Documents\Personal\Hattrick\HO\HattrickOrganizer\db2\database.lck"

 

I will shut down, restart, try to delete .lck file and try again.

**Comment by Crip1** [comment]
Once I deleted the lockfile, I was able to start HO, and it opened up, and things looked fine.

 

Once I tried to download data, I got the same message, Connection to www.hattrick.org <http://www.hattrick.org>  could not be established, Error fetching Matchlineup

 

It then downloads some data, and gives me the option to save a .hrf    I think I tried to save it in the past, I will cancel that for now.

 

Then I get a message, An error occurred 22

 

Details of which are:

 

java.lang.ArrayIndexOutOfBoundsException: 22

                at core.gui.comp.table.TableSorter.getValueAt(TableSorter.java:182)

                at core.gui.model.ReduzedTableModel.getValueAt(ReduzedTableModel.java:56)

                at javax.swing.JTable.getValueAt(Unknown Source)

                at javax.swing.JTable.prepareRenderer(Unknown Source)

                at javax.swing.plaf.synth.SynthTableUI.paintCell(Unknown Source)

                at javax.swing.plaf.synth.SynthTableUI.paintCells(Unknown Source)

                at javax.swing.plaf.synth.SynthTableUI.paint(Unknown Source)

                at javax.swing.plaf.synth.SynthTableUI.update(Unknown Source)

                at javax.swing.JComponent.paintComponent(Unknown Source)

                at javax.swing.JComponent.paint(Unknown Source)

                at javax.swing.JComponent.paintChildren(Unknown Source)

                at javax.swing.JComponent.paint(Unknown Source)

                at javax.swing.JViewport.paint(Unknown Source)

                at javax.swing.JComponent.paintChildren(Unknown Source)

                at javax.swing.JComponent.paint(Unknown Source)

                at javax.swing.JComponent.paintChildren(Unknown Source)

                at javax.swing.JSplitPane.paintChildren(Unknown Source)

                at javax.swing.JComponent.paint(Unknown Source)

                at javax.swing.JComponent.paintChildren(Unknown Source)

                at javax.swing.JComponent.paint(Unknown Source)

                at javax.swing.JComponent.paintToOffscreen(Unknown Source)

                at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)

                at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)

                at javax.swing.RepaintManager.paint(Unknown Source)

                at javax.swing.JComponent._paintImmediately(Unknown Source)

                at javax.swing.JComponent.paintImmediately(Unknown Source)

                at javax.swing.RepaintManager$4.run(Unknown Source)

                at javax.swing.RepaintManager$4.run(Unknown Source)

                at java.security.AccessController.doPrivileged(Native Method)

                at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

                at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)

                at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)

                at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)

                at javax.swing.RepaintManager.access$1200(Unknown Source)

                at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)

                at java.awt.event.InvocationEvent.dispatch(Unknown Source)

                at java.awt.EventQueue.dispatchEventImpl(Unknown Source)

                at java.awt.EventQueue.access$500(Unknown Source)

                at java.awt.EventQueue$3.run(Unknown Source)

                at java.awt.EventQueue$3.run(Unknown Source)

                at java.security.AccessController.doPrivileged(Native Method)

                at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

                at java.awt.EventQueue.dispatchEvent(Unknown Source)

                at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)

                at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)

                at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)

                at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

                at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

                at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Crip1** [comment]
When I next restarted, I got an error message

 

An error occurred

 

Java.lang.NullPointerException     details of which are:

 

java.lang.NullPointerException

                at core.model.match.MatchStatistics.isOldie(MatchStatistics.java:329)

                at core.model.match.MatchStatistics.<init>(MatchStatistics.java:22)

                at core.training.TrainingPreviewPlayers.getMatchesForTraining(TrainingPreviewPlayers.java:249)

                at core.training.TrainingPreviewPlayers.calculateWeeklyTrainingForPlayer(TrainingPreviewPlayers.java:142)

                at core.training.TrainingPreviewPlayers.getTrainPreviewPlayer(TrainingPreviewPlayers.java:76)

                at core.gui.comp.entry.SpielerLabelEntry.updateDisplay(SpielerLabelEntry.java:372)

                at core.gui.comp.entry.SpielerLabelEntry.createComponent(SpielerLabelEntry.java:265)

                at core.gui.comp.entry.SpielerLabelEntry.<init>(SpielerLabelEntry.java:57)

                at core.gui.model.UserColumnFactory$14.getTableEntry(UserColumnFactory.java:277)

                at core.gui.model.PlayerOverviewModel.initData(PlayerOverviewModel.java:163)

                at core.gui.model.PlayerOverviewModel.setValues(PlayerOverviewModel.java:89)

                at module.playerOverview.PlayerOverviewTable.initModel(PlayerOverviewTable.java:144)

                at module.playerOverview.PlayerOverviewTable.<init>(PlayerOverviewTable.java:33)

                at module.playerOverview.SpielerUebersichtsPanel.initSpielerTabelle(SpielerUebersichtsPanel.java:186)

                at module.playerOverview.SpielerUebersichtsPanel.initComponents(SpielerUebersichtsPanel.java:118)

                at module.playerOverview.SpielerUebersichtsPanel.<init>(SpielerUebersichtsPanel.java:43)

                at module.playerOverview.PlayerOverviewModule.createTabPanel(PlayerOverviewModule.java:30)

                at core.gui.comp.tabbedPane.HOTabbedPane.showTab(HOTabbedPane.java:38)

                at core.gui.HOMainFrame.initComponents(HOMainFrame.java:500)

                at core.gui.HOMainFrame.<init>(HOMainFrame.java:190)

                at core.gui.HOMainFrame.instance(HOMainFrame.java:284)

                at core.HO$1.run(HO.java:225)

                at java.awt.event.InvocationEvent.dispatch(Unknown Source)

                at java.awt.EventQueue.dispatchEventImpl(Unknown Source)

                at java.awt.EventQueue.access$500(Unknown Source)

                at java.awt.EventQueue$3.run(Unknown Source)

                at java.awt.EventQueue$3.run(Unknown Source)

                at java.security.AccessController.doPrivileged(Native Method)

                at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

                at java.awt.EventQueue.dispatchEvent(Unknown Source)

                at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)

                at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)

                at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)

                at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

                at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

                at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by manguz** [comment]
Some changes in CHPP code may have broke something in HO, but Devs are surely aware.
You should really use a newer version as it seems yours behave differently.
just swap the DB folder from one installation to another and you are good to go

**Comment by wsbrenk** [comment]
this is a bug on ht side - i hope it will be fixed soon.

**Comment by Crip1** [comment]
Ugh!     I tried upgrading to V5.2, and I couldn’t really get it to work.    It will download today’s data, import transaction history, but I can’t import my old .hrf data, nor can I upload lineups...      Hopefully I can uninstall that, and do an upgrade from within 3.0 once the bug on the HT side has been fixed.

**Comment by wsbrenk** [comment]
chpp fixed errors

**Comment by Crip1** [comment]
Thanks.   Restored a backup, deleted lock files, restarted, everything seems to be working again.
