### ISSUE TITLE
[BUG] TeamAnalyzer Error on initial installation

### ISSUE THREAD

**Issue by masterpatje** [akasolace/HO#1467]
**Describe the bug**
New clean installation. Before downloading team data go to tab TeamAnalyzer. An error occurs. See screenshot.

**To Reproduce**
1. Clean installation
2. Go to 'TeamAnalyzer' (before downloading team data)

**Screenshots**
![image](https://user-images.githubusercontent.com/102049050/163709689-5653a93f-24f4-4c88-80a6-f8666de0335c.png)
**Details**
java.lang.NullPointerException: Cannot invoke "core.model.XtraData.getLeagueLevelUnitID()" because the return value of "core.model.HOModel.getXtraDaten()" is null
	at module.teamAnalyzer.manager.TeamManager.getDivisionMatches(TeamManager.java:145)
	at module.teamAnalyzer.manager.TeamManager.getLeagueMatches(TeamManager.java:28)
	at module.teamAnalyzer.manager.TeamManager.getTeamsMap(TeamManager.java:130)
	at module.teamAnalyzer.manager.TeamManager.getTeamsMap(TeamManager.java:122)
	at module.teamAnalyzer.manager.TeamManager.getFirstTeam(TeamManager.java:23)
	at module.teamAnalyzer.SystemManager.initialize(SystemManager.java:140)
	at module.teamAnalyzer.ui.TeamAnalyzerPanel.initialize(TeamAnalyzerPanel.java:33)
	at core.gui.comp.panel.LazyPanel.callInitialize(LazyPanel.java:150)
	at core.gui.comp.panel.LazyPanel$2.hierarchyChanged(LazyPanel.java:137)
	at java.desktop/java.awt.Component.processHierarchyEvent(Component.java:6793)
	at java.desktop/java.awt.Component.processEvent(Component.java:6412)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.Component.createHierarchyEvents(Component.java:5639)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1474)
	at java.desktop/java.awt.Component.show(Component.java:1691)
	at java.desktop/java.awt.Component.show(Component.java:1728)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/javax.swing.JComponent.setVisible(JComponent.java:2720)
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:422)
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:295)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:148)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:79)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:648)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:623)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:4101)
	at java.desktop/javax.swing.plaf.synth.SynthTabbedPaneUI$1.mousePressed(SynthTabbedPaneUI.java:320)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Platform information:**
 - OS: Windows 10
 - Version 6.0 v277

**Additional context**
**Output.log**
11:59:03 [Error]   core.util.ExceptionHandler: java.lang.NullPointerException: Cannot invoke "core.model.XtraData.getLeagueLevelUnitID()" because the return value of "core.model.HOModel.getXtraDaten()" is null
11:59:03 [Error]   core.util.ExceptionHandler: module.teamAnalyzer.manager.TeamManager.getDivisionMatches(TeamManager.java:145)
11:59:03 [Error]   core.util.ExceptionHandler: module.teamAnalyzer.manager.TeamManager.getLeagueMatches(TeamManager.java:28)
11:59:03 [Error]   core.util.ExceptionHandler: module.teamAnalyzer.manager.TeamManager.getTeamsMap(TeamManager.java:130)
11:59:03 [Error]   core.util.ExceptionHandler: module.teamAnalyzer.manager.TeamManager.getTeamsMap(TeamManager.java:122)
11:59:03 [Error]   core.util.ExceptionHandler: module.teamAnalyzer.manager.TeamManager.getFirstTeam(TeamManager.java:23)
11:59:03 [Error]   core.util.ExceptionHandler: module.teamAnalyzer.SystemManager.initialize(SystemManager.java:140)
11:59:03 [Error]   core.util.ExceptionHandler: module.teamAnalyzer.ui.TeamAnalyzerPanel.initialize(TeamAnalyzerPanel.java:33)
11:59:03 [Error]   core.util.ExceptionHandler: core.gui.comp.panel.LazyPanel.callInitialize(LazyPanel.java:150)
11:59:03 [Error]   core.util.ExceptionHandler: core.gui.comp.panel.LazyPanel$2.hierarchyChanged(LazyPanel.java:137)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.processHierarchyEvent(Component.java:6793)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.processEvent(Component.java:6412)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Container.processEvent(Container.java:2266)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.createHierarchyEvents(Component.java:5639)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1474)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.show(Component.java:1691)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.show(Component.java:1728)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.setVisible(Component.java:1675)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.JComponent.setVisible(JComponent.java:2720)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:422)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:295)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:148)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:79)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:648)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:623)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:4101)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.plaf.synth.SynthTabbedPaneUI$1.mousePressed(SynthTabbedPaneUI.java:320)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.processEvent(Component.java:6391)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Container.processEvent(Container.java:2266)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
11:59:03 [Error]   core.util.ExceptionHandler: java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
11:59:03 [Error]   core.util.ExceptionHandler: java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
11:59:03 [Error]   core.util.ExceptionHandler: java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
11:59:03 [Error]   core.util.ExceptionHandler: java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
11:59:03 [Error]   core.util.ExceptionHandler: java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
11:59:03 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by masterpatje** [comment]
Fixed.
