### ISSUE TITLE
[BUG] re-importing a HRF files gives an unrecoverable error

### ISSUE THREAD

**Issue by masterpatje** [akasolace/HO#1481]
**Describe the bug**
I think that it is related to the #1469 fix. Importing HRF files is working properly and re-importing the same files was handled fine previously, but now when I again import the same HRF files I get an error. I did this because from a testing purpose I was importing the files one-by-one and multiple HRF files and then when importing more HRF files which also included the HRF files previously imported I got an error.

**To Reproduce**
See description.

**Screenshots**
![image](https://user-images.githubusercontent.com/102049050/164973866-140d70e4-2c98-4fc5-bf6e-e6ea099c14ea.png)

**Platform information:**
 - OS: Windows 10
 - Version 6.0.284

**Additional context**
**Output.log**
[Info]    TrainingWeekManager: Next week training date: 2022-04-29 01:05:00
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Debug]   TrainingModel: Previous training date: TrainingPerWeek[Training date: 2022-04-22 01:05:00, Training Type: Playmaking%, Intensity: 100%, StaminaPart: 17]
 [Debug]   FutureTrainingTable: FutureTraining table has been cleared !
 [Debug]   TrainingModel: Previous training date: TrainingPerWeek[Training date: 2022-04-22 01:05:00, Training Type: Playmaking%, Intensity: 100%, StaminaPart: 17]
 [Debug]   FutureTrainingTable: FutureTraining table has been cleared !
 [Debug]   TeamsLogoTable: team with no logo team ID=365613
 [Debug]   ThemeManager: logo not found for team 365613
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Info]    TrainingWeekManager: Next week training date: 2022-04-29 01:05:00
 [Debug]   TrainingModel: Previous training date: TrainingPerWeek[Training date: 2022-04-22 01:05:00, Training Type: Playmaking%, Intensity: 100%, StaminaPart: 17]
 [Debug]   FutureTrainingTable: FutureTraining table has been cleared !
 [Debug]   TrainingModel: Previous training date: TrainingPerWeek[Training date: 2022-04-22 01:05:00, Training Type: Playmaking%, Intensity: 100%, StaminaPart: 17]
 [Debug]   FutureTrainingTable: FutureTraining table has been cleared !
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Info]    TrainingWeekManager: Next week training date: 2022-04-29 01:05:00
 [Debug]   TrainingModel: Previous training date: TrainingPerWeek[Training date: 2022-04-22 01:05:00, Training Type: Playmaking%, Intensity: 100%, StaminaPart: 17]
 [Debug]   FutureTrainingTable: FutureTraining table has been cleared !
 [Debug]   TrainingModel: Previous training date: TrainingPerWeek[Training date: 2022-04-22 01:05:00, Training Type: Playmaking%, Intensity: 100%, StaminaPart: 17]
 [Debug]   FutureTrainingTable: FutureTraining table has been cleared !
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Info]    TrainingWeekManager: Next week training date: 2022-04-29 01:05:00
 [Debug]   TrainingModel: Previous training date: TrainingPerWeek[Training date: 2022-04-22 01:05:00, Training Type: Playmaking%, Intensity: 100%, StaminaPart: 17]
 [Debug]   FutureTrainingTable: FutureTraining table has been cleared !
 [Debug]   TrainingModel: Previous training date: TrainingPerWeek[Training date: 2022-04-22 01:05:00, Training Type: Playmaking%, Intensity: 100%, StaminaPart: 17]
 [Debug]   FutureTrainingTable: FutureTraining table has been cleared !
 [Debug]   Verein: Konstruktor Verein: java.sql.SQLException: invalid cursor state: identifier cursor not positioned on row in UPDATE, DELETE, SET, or GET statement: ; ResultSet is empty
 [Error]   TeamTable: Error while loading Team model: java.sql.SQLException: invalid cursor state: identifier cursor not positioned on row in UPDATE, DELETE, SET, or GET statement: ; ResultSet is empty
 [Debug]   Basics: Constructor Basics: java.sql.SQLException: invalid cursor state: identifier cursor not positioned on row in UPDATE, DELETE, SET, or GET statement: ; ResultSet is empty
 [Debug]   EconomyTable: DatenbankZugriff.getFinanzen: java.sql.SQLException: invalid cursor state: identifier cursor not positioned on row in UPDATE, DELETE, SET, or GET statement: ; ResultSet is empty
 [Debug]   Liga: Konstruktor Liga : java.sql.SQLException: invalid cursor state: identifier cursor not positioned on row in UPDATE, DELETE, SET, or GET statement: ; ResultSet is empty
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   HOMainFrame: Currency changed failed! Cannot invoke "core.model.XtraData.getCurrencyRate()" because the return value of "core.model.HOModel.getXtraDaten()" is null
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Error]   MyConnector: CHPP Error - 50 - Unknown TeamID (50) Additional Info: 0
java.lang.RuntimeException: CHPP Error - 50 - Unknown TeamID (50) Additional Info: 0
	at core.net.MyConnector.getCHPPWebFile(MyConnector.java:683)
	at core.net.MyConnector.getHattrickXMLFile(MyConnector.java:209)
	at module.transfer.XMLParser.getAllTeamTransfers(XMLParser.java:132)
	at core.db.TransferTable.updateTeamTransfers(TransferTable.java:123)
	at core.db.DBManager.updateTeamTransfers(DBManager.java:1789)
	at module.transfer.TransfersPanel.refresh(TransfersPanel.java:83)
	at core.gui.RefreshManager.doReInit(RefreshManager.java:52)
	at core.file.hrf.HRFImport.<init>(HRFImport.java:87)
	at core.gui.HOMainFrame.actionPerformed(HOMainFrame.java:306)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by masterpatje** [comment]
I did a few more test. It only gives a problem when a HRF file is already in the database. New HRF files are handled correctly. But when this problem occurs it corrupts the database, no players are visible anymore in the "squad".

**Comment by wsbrenk** [comment]
@masterpatje unfortunately I could not reproduce the error. I suspect that possibly the hrf file could be broken.  I tried to do something about it.

please check the hrf file, if there is something wrong inside

**Comment by masterpatje** [comment]
Thanks for checking. I will test it again (the new version). And see if I can locate the HRF file that gives the error. In that case it must have been one of the newer HRF files, because I didn't have this problem before.

**Comment by masterpatje** [comment]
Is there an easy way to check if a HRF file is broken? If I import a file which is corrupt do I get an error in the output.log normally?

**Comment by masterpatje** [comment]
In #1469 I described that I imported HRF files one at a time. I decided to close the application to make sure there is not something running in the background. After I re-opened it and AGAIN imported the HRF file of today (24/4/22) and checking the checkbox "apply to all" I again got the error. I will do a clean installation and will check if it has something to do with the checkbox.

I am absolutely sure the 24/4/22 works properly because it is the download file for the team.

![image](https://user-images.githubusercontent.com/102049050/164998159-530ef34c-fb27-4002-b589-700bb154cc9e.png)

![image](https://user-images.githubusercontent.com/102049050/164998260-297d164d-bc08-4b26-b8dc-e6eda9ac5dbd.png)

**Output.log**
23:48:56 [Info]    core.HO: VERSION: 6.0   versionType:  DEV   RevisionNumber: 285
23:48:57 [Info]    core.model.HOVerwaltung: language used for interface is: English
23:48:57 [Info]    core.training.TrainingWeekManager: Next week training date: 2022-04-29 01:05:00
23:48:57 [Info]    core.gui.HOMainFrame: This is HO! version 6.0 DEV (r285), have fun!
23:48:57 [Info]    core.gui.HOMainFrame: Operating system found: Windows 10 on amd64 (10.0)
23:48:57 [Info]    core.gui.HOMainFrame: Using java: 17.0.1 (Eclipse Adoptium)
23:49:49 [Error]   core.db.TeamTable: Error while loading Team model: java.sql.SQLException: invalid cursor state: identifier cursor not positioned on row in UPDATE, DELETE, SET, or GET statement: ; ResultSet is empty
23:49:50 [Error]   core.net.MyConnector: CHPP Error - 50 - Unknown TeamID (50) Additional Info: 0
java.lang.RuntimeException: CHPP Error - 50 - Unknown TeamID (50) Additional Info: 0
	at core.net.MyConnector.getCHPPWebFile(MyConnector.java:683)
	at core.net.MyConnector.getHattrickXMLFile(MyConnector.java:209)
	at module.transfer.XMLParser.getAllTeamTransfers(XMLParser.java:132)
	at core.db.TransferTable.updateTeamTransfers(TransferTable.java:123)
	at core.db.DBManager.updateTeamTransfers(DBManager.java:1789)
	at module.transfer.TransfersPanel.refresh(TransfersPanel.java:83)
	at core.gui.RefreshManager.doReInit(RefreshManager.java:52)
	at core.file.hrf.HRFImport.<init>(HRFImport.java:87)
	at core.gui.HOMainFrame.actionPerformed(HOMainFrame.java:306)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by masterpatje** [comment]
Tested it again (now with a HRF file from 25/4/22) and this time I did not check the checkbox. And got the same error.
![image](https://user-images.githubusercontent.com/102049050/164998725-337d7b64-cc7a-4549-8fb5-4f80b874cf1d.png)

**Next test. Clean installation and I will test if I select "No" when asked to store the file in the database.**

**Comment by masterpatje** [comment]
This time I tested it with only importing HRF files (instead of first downloading a HRF file and then importing HRF files) to simplify the process. And I could determine that the error is occuring when the re-imported file is stored in the database. 

When selecting NO it cancels the HRF-file import and no error occurs. (Note: what is the difference between No and Cancel? The same function?)

When re-importing a file the error occurs. Storing a file in the database that was already imported does not make much sense. 
**Proposed solution:** These files should not be imported in the database automatically. This will solve the problem directly as it is clear to me from the test that it has to do with storing the files in the database when the file was already imported.

**Note:** only thing that I could think of that makes it usefull to re-import files that are already in the database (but still not store them in the database when doing so!!) is if they update the past training table. This could be usefull for users who wants to make use of the new functionality of the adjusted past training table that already have the HRF files in the database and thus don't adjust the past training table. Or maybe you can force setting the past training table via another option like in the menu with the recalculation subskills (7 weeks) or maybe even integrated in that functionality? So that you can just skip files that are already in the database all together when they are re-imported.

I am interested in your thoughts on this one.

![image](https://user-images.githubusercontent.com/102049050/164998922-6ba15f02-e777-4dcd-a80e-460f5c954c5b.png)

![image](https://user-images.githubusercontent.com/102049050/164998908-f16566e7-5201-4c03-967a-6fe6d2c81486.png)

**Output.log**
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Info]    TrainingWeekManager: Next week training date: 2022-04-29 01:05:00
 [Debug]   ThemeManager: avatar for player 434040548 not found locally. It will be downloaded
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   ThemeManager: avatar for player 434040548 not found locally. It will be downloaded
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Info]    TrainingWeekManager: Next week training date: 2022-04-29 01:05:00
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   ThemeManager: avatar for player 434040548 not found locally. It will be downloaded
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Info]    TrainingWeekManager: Next week training date: 2022-04-29 01:05:00

![image](https://user-images.githubusercontent.com/102049050/164998995-1e2664e0-5d52-435e-9068-373f56f9c8fb.png)

![image](https://user-images.githubusercontent.com/102049050/164998963-6646292b-f022-452f-8115-812fba3cd0a3.png)

 
 [Debug]   Verein: Konstruktor Verein: java.sql.SQLException: invalid cursor state: identifier cursor not positioned on row in UPDATE, DELETE, SET, or GET statement: ; ResultSet is empty
 [Error]   TeamTable: Error while loading Team model: java.sql.SQLException: invalid cursor state: identifier cursor not positioned on row in UPDATE, DELETE, SET, or GET statement: ; ResultSet is empty
 [Debug]   Basics: Constructor Basics: java.sql.SQLException: invalid cursor state: identifier cursor not positioned on row in UPDATE, DELETE, SET, or GET statement: ; ResultSet is empty
 [Debug]   EconomyTable: DatenbankZugriff.getFinanzen: java.sql.SQLException: invalid cursor state: identifier cursor not positioned on row in UPDATE, DELETE, SET, or GET statement: ; ResultSet is empty
 [Debug]   Liga: Konstruktor Liga : java.sql.SQLException: invalid cursor state: identifier cursor not positioned on row in UPDATE, DELETE, SET, or GET statement: ; ResultSet is empty
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Error]   MyConnector: CHPP Error - 50 - Unknown TeamID (50) Additional Info: 0
java.lang.RuntimeException: CHPP Error - 50 - Unknown TeamID (50) Additional Info: 0
	at core.net.MyConnector.getCHPPWebFile(MyConnector.java:683)
	at core.net.MyConnector.getHattrickXMLFile(MyConnector.java:209)
	at module.transfer.XMLParser.getAllTeamTransfers(XMLParser.java:132)
	at core.db.TransferTable.updateTeamTransfers(TransferTable.java:123)
	at core.db.DBManager.updateTeamTransfers(DBManager.java:1789)
	at module.transfer.TransfersPanel.refresh(TransfersPanel.java:83)
	at core.gui.RefreshManager.doReInit(RefreshManager.java:52)
	at core.file.hrf.HRFImport.<init>(HRFImport.java:87)
	at core.gui.HOMainFrame.actionPerformed(HOMainFrame.java:306)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by wsbrenk** [comment]
found it. Never tried to reimport latest hrf file;-(

**Comment by masterpatje** [comment]
Fixed in v288.

**Comment by masterpatje** [comment]
**New unexpected behaviour:**
The subskills are available after downloading today's HRF file. But when re-importing the downloaded today's HRF file the subskills are removed and are visible that they are substracted (see screenshot by selecting the comparing file as today's file). This might be intended behaviour in the way that it is programmed. So please verify if this is what you wanted.

![image](https://user-images.githubusercontent.com/102049050/165286907-03a54847-0bc4-4ca8-a27d-64b462cf1ce7.png)

I think that this is connected to #1469 in the way that subskills are not updated on importing previous HRF files.

So when the latest HRF file is imported it overwrites the current HRF file, but also the subskills are no longer available. 

Clear enough?

**Comment by wsbrenk** [comment]
@masterpatje reimporting of hrf files does not invoke the subskill calculation. instead the subs are cleared. that is what you see.
user's have to recalculate the subskills (7 weeks) on demand to reset the subskills.

**Comment by masterpatje** [comment]
Ok intended behaviour. Thanks for clarifying.
