### ISSUE TITLE
[BUG]update of portable HO5.2 does not succeed

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1545]
first start after update gives: 

java.lang.UnsupportedClassVersionError: core/HOLauncher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 59.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:825)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:723)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:646)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:80)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

the jre folder is not updated

**Comment by wsbrenk** [comment]
~~~
    public static String get_HO_zip_download_url(String full_version, double version, String versionType) {

        return switch (versionType) {
            case "DEV" -> "https://github.com/akasolace/HO/releases/download/dev/HO-" + full_version + "-portable-win-DEV.zip";
            case "BETA" -> "https://github.com/akasolace/HO/releases/download/beta/HO-" + full_version + "-portable-win-BETA.zip";
            default -> "https://github.com/akasolace/HO/releases/download/tag_stable/HO-" + full_version + "-portable-win.zip";
        };
    }
~~~

portable update seems to work only on windows and this only if java remains unchanged.

**Comment by wsbrenk** [comment]
portable HO6 will download the jre-zips

**Comment by wsbrenk** [comment]
older HO installations have to be updated manually
* download zip - asset 
* extract zip to destination folder 
* adjust java if not included in zip
