### ISSUE TITLE
[eBUG] Error when removing player from penalty takers

### ISSUE THREAD

**Issue by cheilson** [akasolace/HO#158]
I get an error when removing a player from penalty takers.

**To Reproduce**
1. Go to penalty takers
2. Click on remove all
3. Click on auto add, HO also adds subs amongst the 11 best takers.
4. Uncheck show subs and show others
5. Remove a sub from the 11, end this occurs:

java.lang.IllegalArgumentException: Row index out of range
at javax.swing.JTable.boundRow(Unknown Source)
at javax.swing.JTable.addRowSelectionInterval(Unknown Source)
at module.lineup.penalties.PenaltyTakersView.select(PenaltyTakersView.java:522)
at module.lineup.penalties.PenaltyTakersView.selectPlayers(PenaltyTakersView.java:531)
at module.lineup.penalties.PenaltyTakersView.access$2100(PenaltyTakersView.java:51)
at module.lineup.penalties.PenaltyTakersView$10.actionPerformed(PenaltyTakersView.java:464)
at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Window.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)

**Platform information:**
 - OS: [Windows 10 Home]
 - Version (including build number)

**Comment by akasolace** [comment]
anyone can confirm that bug ?

**Comment by yaute74** [comment]
@akasolace yes I reproduce it

**Comment by akasolace** [comment]
@yaute74 ok thanks for confirming it ... so I put that one to be fixed for 2.0 release ...

**Comment by akasolace** [comment]
I also confirm the bug
as a side question, I really dont see what the benefit of having show others ...

**Comment by akasolace** [comment]
I believe this bug has been here for ever.
