### ISSUE TITLE
[BUG] Age of Players negative , Dates of HRF incorrect

### ISSUE THREAD

**Issue by Marcx87** [akasolace/HO#1580]
I upgraded from latest stable release ( 5.2.3945.2 ) to pre-release 6 ( 6.0.341.1 ).

Upgrade steps:
1) Downloaded version HO-6.0.341.1-portable-win-BETA-JRE.zip 
2) Unzip file
3) copy db folder from HO5 to HO6 folder
4) open HO.exe

Age of Players are smilar to -171129
Years of date in HRF frame are like 54505 and day/month are not correct.

HO Languange IT-it

![image](https://user-images.githubusercontent.com/3596695/179263753-2f6e59ad-8860-4ae1-a88a-e9f0b94cfca4.png)

**Comment by wsbrenk** [comment]
@Marcx87 what does the clock of your computer show. is it perhaps set incorrectly? If not, please upload the log file. you find it in %APPDATA%/ho/logs

**Comment by wsbrenk** [comment]
the output.log of my try to reproduce this:

~~~
 [Info]    HO: users.json file not found => a new one will be created
 [Info]    HO: VERSION: 6.0   versionType:  BETA   RevisionNumber: 341
 [Info]    DBUpdater: Sponsor Bonus columns have been added to Economy table
 [Info]    DBUpdater: SPIELER table structure has been updated
 [Info]    DBUpdater: Update to 600 done. Updating DBVersion
 [Info]    DBUpdater: Update complete, setting DBVersion to 601
 [Error]   UserConfigurationTable: parameter lineupIncludeHTO is not stored in UserConfigurationTable
 [Error]   UserConfigurationTable: parameter lineupIncludeTemplates is not stored in UserConfigurationTable
 [Info]    HOVerwaltung: language used for interface is: English
 [Info]    TrainingWeekManager: Next week training date: 2022-07-08 00:30:00
 [Info]    HOMainFrame: This is HO! version 6.0 BETA (r341), have fun!
 [Info]    HOMainFrame: Operating system found: Windows 10 on amd64 (10.0)
 [Info]    HOMainFrame: Using java: 17.0.1 (Eclipse Adoptium)
 [Debug]   FileLoader: File will not be searched anymore: /prediction\predictionTypes.conf
 [Debug]   RatingPredictionManager: Rebuilding RPM cache!
 [Debug]   ThemeManager: avatar for player 451269636 not found locally. It will be downloaded
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
 [Debug]   ThemeManager: avatar for player 453419222 not found locally. It will be downloaded
 [Info]    ThemeManager: Donwloading player's avatar: 1/33
 [Info]    ThemeManager: Donwloading player's avatar: 2/33
 [Info]    ThemeManager: Donwloading player's avatar: 3/33
 [Info]    ThemeManager: Donwloading player's avatar: 4/33
 [Info]    ThemeManager: Donwloading player's avatar: 5/33
 [Info]    ThemeManager: Donwloading player's avatar: 6/33
 [Info]    ThemeManager: Donwloading player's avatar: 7/33
 [Info]    ThemeManager: Donwloading player's avatar: 8/33
 [Info]    ThemeManager: Donwloading player's avatar: 9/33
 [Info]    ThemeManager: Donwloading player's avatar: 10/33
 [Info]    ThemeManager: Donwloading player's avatar: 11/33
 [Info]    ThemeManager: Donwloading player's avatar: 12/33
 [Info]    ThemeManager: Donwloading player's avatar: 13/33
 [Info]    ThemeManager: Donwloading player's avatar: 14/33
 [Info]    ThemeManager: Donwloading player's avatar: 15/33
 [Info]    ThemeManager: Donwloading player's avatar: 16/33
 [Info]    ThemeManager: Donwloading player's avatar: 17/33
 [Info]    ThemeManager: Donwloading player's avatar: 18/33
 [Info]    ThemeManager: Donwloading player's avatar: 19/33
 [Info]    ThemeManager: Donwloading player's avatar: 20/33
 [Info]    ThemeManager: Donwloading player's avatar: 21/33
 [Info]    ThemeManager: Donwloading player's avatar: 22/33
 [Info]    ThemeManager: Donwloading player's avatar: 23/33
 [Info]    ThemeManager: Donwloading player's avatar: 24/33
 [Info]    ThemeManager: Donwloading player's avatar: 25/33
 [Info]    ThemeManager: Donwloading player's avatar: 26/33
 [Info]    ThemeManager: Donwloading player's avatar: 27/33
 [Info]    ThemeManager: Donwloading player's avatar: 28/33
 [Info]    ThemeManager: Donwloading player's avatar: 29/33
 [Info]    ThemeManager: Donwloading player's avatar: 30/33
 [Info]    ThemeManager: Donwloading player's avatar: 31/33
 [Info]    ThemeManager: Donwloading player's avatar: 32/33
 [Info]    ThemeManager: Donwloading player's avatar: 33/33
 [Debug]   TrainingManager: HOVerwaltung model changed => TrainingManager and TrainingWeekManager are reinitialized
 [Debug]   OnlineWorker: Get Lineup : 696406556
 [Debug]   OnlineWorker: Get Lineup : 692411332
 [Debug]   OnlineWorker: Get Lineup : 696498148
 [Debug]   OnlineWorker: Get Lineup : 696617123
 [Debug]   OnlineWorker: Get Lineup : 696678302
 [Debug]   OnlineWorker: Get Lineup : 692411329
 [Debug]   OnlineWorker: Get Lineup : 692411330
 [Debug]   OnlineWorker: Get Lineup : 692411331
 [Debug]   TeamsLogoTable: storeTeamLogoInfo: logo URI was null for team 645419
 [Info]    TrainingWeekManager: Next week training date: 2022-07-22 00:30:00
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
~~~

everythind seems to be fine after this.

**Comment by wsbrenk** [comment]
change the logging (displaying errors was wrong):
~~~
[Info]    DBUpdater: Sponsor Bonus columns have been added to Economy table
 [Info]    DBUpdater: SPIELER table structure has been updated
 [Debug]   DBUpdater: Update to 600 done but this is a development version so DBVersion will remain unchanged
 [Debug]   DBUpdater: Update to 601 complete but this is a development version so DBVersion will remain unchanged
 [Info]    UserConfigurationTable: parameter lineupIncludeHTO is not stored in UserConfigurationTable. Default is used: false
 [Info]    UserConfigurationTable: parameter lineupIncludeTemplates is not stored in UserConfigurationTable. Default is used: false
 [Info]    HOVerwaltung: language used for interface is: English
 [Debug]   DBConfigUpdater: Updating configuration to version 5.0  ...
 [Info]    TrainingWeekManager: Next week training date: 2022-07-08 00:30:00
 [Info]    HOMainFrame: This is HO! version 0.0 DEV (r0), have fun!
 [Info]    HOMainFrame: Operating system found: Windows 11 on amd64 (10.0)
 [Info]    HOMainFrame: Using java: 17.0.3 (Eclipse Adoptium)
 [Debug]   RatingPredictionManager: Rebuilding RPM cache!
 [Debug]   LineupRatingAssistantPanel:  refresh() has been called
 [Debug]   LineupPositionsPanel: refresh() has been called
~~~

**Comment by Marcx87** [comment]
Hi,

thank you, I try to be more precise possibile...

Until 10~ days ago I was using HO 1.437
Then I upgraded from 1.437 -> to Ho3 -> to HO5
I downloaded HO3 because database version was to old.


Now I am using HO 5 without any issue, while HO6 has the error I reported.

The installation of both HO 5 and 6 are Win64 Portable WITH JRE.

My configuration is
Windows 10 
Language English (US) Regional Format (italy, ie the date is formatted in dd/MM/yyyy )
![image](https://user-images.githubusercontent.com/3596695/179416875-804f70b4-3bde-4a61-b341-be032943622e.png)

This is player status in HO5
![image](https://user-images.githubusercontent.com/3596695/179416892-b201b110-b0d7-4445-8406-6d6e03802edc.png)

This is Compare HRF in HO5
![image](https://user-images.githubusercontent.com/3596695/179416903-48e4ff90-8f88-4089-adf9-0573f1b6d5d4.png)

This is player status in HO 6.0.346.1 (below I will attach the logs file for the first start from 5 to 6)
![image](https://user-images.githubusercontent.com/3596695/179417032-7a5ed1a6-aa46-4746-9710-9a35d7d27d76.png)

This is Compare HRF in HO 6.0.346.1
![image](https://user-images.githubusercontent.com/3596695/179417042-ddaa56e7-e220-4d68-a81d-77cf58f845d1.png)

The output and HO log file are both 4.1MB each and I only opened HO.

There are a lot of similar errors: 

On initialization I have this two errors

```
[Error]   JDBCAdapter: JDBCAdapter.executeUpdate : java.sql.SQLException: Access is denied in statement [SET TABLE MATCHHIGHLIGHTS NEW SPACE]
Statement: SET TABLE MATCHHIGHLIGHTS NEW SPACE
java.sql.SQLException: Access is denied in statement [SET TABLE MATCHHIGHLIGHTS NEW SPACE]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.executeUpdate(Unknown Source)
	at core.db.JDBCAdapter.executeUpdate(JDBCAdapter.java:90)
	at core.db.DBUpdater.updateDBv600(DBUpdater.java:89)
	at core.db.DBUpdater.updateDB(DBUpdater.java:62)
	at core.db.DBManager.instance(DBManager.java:217)
	at core.HO.main(HO.java:150)
	at core.HOLauncher.main(HOLauncher.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: org.hsqldb.HsqlException: Access is denied
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.StatementCommand.getResult(Unknown Source)
	at org.hsqldb.StatementCommand.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 15 more

 [Error]   JDBCAdapter: JDBCAdapter.executeUpdate : java.sql.SQLException: Access is denied in statement [SET TABLE MATCHLINEUPPLAYER NEW SPACE]
Statement: SET TABLE MATCHLINEUPPLAYER NEW SPACE
java.sql.SQLException: Access is denied in statement [SET TABLE MATCHLINEUPPLAYER NEW SPACE]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.executeUpdate(Unknown Source)
	at core.db.JDBCAdapter.executeUpdate(JDBCAdapter.java:90)
	at core.db.DBUpdater.updateDBv600(DBUpdater.java:90)
	at core.db.DBUpdater.updateDB(DBUpdater.java:62)
	at core.db.DBManager.instance(DBManager.java:217)
	at core.HO.main(HO.java:150)
	at core.HOLauncher.main(HOLauncher.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: org.hsqldb.HsqlException: Access is denied
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.StatementCommand.getResult(Unknown Source)
	at org.hsqldb.StatementCommand.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 15 more
```

Than I have a lot of errors on dates


```
Statement: select * from HRF where DATUM < '54512-05-20 17:06:40.0' order by DATUM desc LIMIT 1
java.sql.SQLSyntaxErrorException: incompatible data types in combination
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.executeQuery(Unknown Source)
	at core.db.JDBCAdapter.executeQuery(JDBCAdapter.java:58)
	at core.db.HRFTable.loadHRF(HRFTable.java:205)
	at core.db.HRFTable.loadLatestHRFDownloadedBefore(HRFTable.java:181)
	at core.db.DBManager.loadLatestHRFDownloadedBefore(DBManager.java:913)
	at core.model.HOModel.<init>(HOModel.java:81)
	at core.model.HOVerwaltung.loadModel(HOVerwaltung.java:203)
	at core.model.HOVerwaltung.loadLatestHoModel(HOVerwaltung.java:126)
	at core.HO.main(HO.java:184)
	at core.HOLauncher.main(HOLauncher.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: org.hsqldb.HsqlException: incompatible data types in combination
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.ExpressionLogical.resolveTypesForComparison(Unknown Source)
	at org.hsqldb.ExpressionLogical.resolveTypes(Unknown Source)
	at org.hsqldb.QuerySpecification.resolveExpressionTypes(Unknown Source)
	at org.hsqldb.QuerySpecification.resolveTypesPartOne(Unknown Source)
	at org.hsqldb.QueryExpression.resolve(Unknown Source)
	at org.hsqldb.ParserDQL.compileCursorSpecification(Unknown Source)
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)
	at org.hsqldb.ParserCommand.compileStatements(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 18 more
```

This is the log file.
[HO-2022-07-17.log](https://github.com/akasolace/HO/files/9128190/HO-2022-07-17.log)

If you need a copy of the database please tell me because is 532MB compressed.

**Comment by wsbrenk** [comment]
I suspect that from the old database some corrupt records are included in the table HRF. could you please try to check with 

Debug->sql editor 

the command:  select * from  HRF order by Datum desc

![image](https://user-images.githubusercontent.com/11821502/179424064-8bd36300-210c-42e1-8ac6-9e2957fed3a0.png)

**Comment by Marcx87** [comment]
I tried sql editor and it seems the all the data fields are incorrect...

I could not  verifiy the db on the previous version.
![ho6sql](https://user-images.githubusercontent.com/3596695/179491413-8fafc4bc-4de8-4d70-86e1-c6fa8e9c9612.PNG)
![ho6sql2](https://user-images.githubusercontent.com/3596695/179491417-226412d4-addb-47da-af9e-06cc77eccb7d.PNG)
![ho6sql3](https://user-images.githubusercontent.com/3596695/179491419-9dd58d96-e1e7-4d1b-b36b-4f05ca016023.PNG)
![ho6sql4](https://user-images.githubusercontent.com/3596695/179491421-87dbb49f-00a1-4e59-a005-74715e0c5b7e.PNG)

**Comment by Marcx87** [comment]
I investigated a bit more into the problem and opened the database of HO5

![image](https://user-images.githubusercontent.com/3596695/179581805-187c377e-d640-4254-98a4-cab89a1d258b.png)

![image](https://user-images.githubusercontent.com/3596695/179581856-7ed0075f-b9e4-4323-9597-b0a7aa34ab2d.png)

![image](https://user-images.githubusercontent.com/3596695/179581995-6ba4cfae-e99f-406d-8e81-b0301d615a0c.png)


The strange this is that in HO5 I got the date properly formatted and with no errors...

**Comment by Marcx87** [comment]
I did another test and I think it is maybe related to the jdbc driver.

I opened the same database from HO3 using hsqldb 2.5.0 and hdbsql 2.6.1 (latest) 

The test was performed in the following way:
- Copy the db from ho 1.4x to a new HO3 installation
- opened HO3 to perform the normal upgrades.
- Use an external db browser to open the db
- Using 2.5.0 driver version, perform the select then disconnect  (date ok)
- Using 2.6.1 driver version, perform the select then disconnect  (date error)
- Using 2.5.0 driver version again, perform the select then disconnect (**date still ok**)

This is 2.5.0 version

```
<!-- https://mvnrepository.com/artifact/org.hsqldb/hsqldb -->
<dependency>
    <groupId>org.hsqldb</groupId>
    <artifactId>hsqldb</artifactId>
    <version>2.5.0</version>
    <scope>test</scope>
</dependency>
```


![hsql 2 5 0](https://user-images.githubusercontent.com/3596695/179633024-f722196e-6824-452b-8052-3ba1af63aa7f.png)

This is 2.6.1 version 
```
<!-- https://mvnrepository.com/artifact/org.hsqldb/hsqldb -->
<dependency>
    <groupId>org.hsqldb</groupId>
    <artifactId>hsqldb</artifactId>
    <version>2.6.1</version>
    <scope>test</scope>
</dependency>

```

![hsql 2 6 1](https://user-images.githubusercontent.com/3596695/179633031-7c0e3d7c-a75c-499b-8d9f-e69eb6bb485e.png)

**Comment by wsbrenk** [comment]
great analysis - i will work on it soon (when harvest is done;-)
maybe the next version of hsqldb (2.7.0) is the solution!?

**Comment by wsbrenk** [comment]
@Marcx87  latest beta uses hsqldb2.5.0. it would be great if you could test it again. hopefully it fixes the issue.
