### ISSUE TITLE
Matches tab

### ISSUE THREAD

**Issue by DavidatorusF** [akasolace/HO#16]
https://snag.gy/odZiP6.jpg

in 1435, we can't remove match for download it again
the linuep stay empty and tab ratings and so one don't give any result

in 1434, still work
https://snag.gy/odZiP6.jpg

**Comment by akasolace** [comment]
You put twice the screenshot of 1.434.
I can confirm that delete match is broken in 1.435 (surely a bug I introduced when I changed the db structure) should not take long to fix it
Regarding other bugs you mentioned I can't reproduce (at least not under windows) . The lineup and other information are properly displayed for me. Does the bug appear after you try to delete a match or is it from the beginning?

**Comment by DavidatorusF** [comment]
fresh install from HO_14341_r2698.zip
run a first time HO for get the code
then a second time for get my old matches
![image](https://user-images.githubusercontent.com/45043004/48563065-cdaa7f00-e8f3-11e8-9ed1-d899f4a63dfd.png)
in matches Tab I have all fine
for exemple, I select my match against FCNemo
![image](https://user-images.githubusercontent.com/45043004/48563229-2712ae00-e8f4-11e8-912b-dde735c6def6.png)
![image](https://user-images.githubusercontent.com/45043004/48563260-37c32400-e8f4-11e8-843e-81989e4793ff.png)
![image](https://user-images.githubusercontent.com/45043004/48563307-4f9aa800-e8f4-11e8-921f-f333cd935778.png)
![image](https://user-images.githubusercontent.com/45043004/48563339-62ad7800-e8f4-11e8-8680-c16fe3493ddf.png)
![image](https://user-images.githubusercontent.com/45043004/48563370-7527b180-e8f4-11e8-8d63-94462cfac3b5.png)
delete/reload a match work

now the same with HO_1.435-DEV-2
![image](https://user-images.githubusercontent.com/45043004/48563627-07c85080-e8f5-11e8-86c4-3764232a828c.png)
![image](https://user-images.githubusercontent.com/45043004/48563657-19115d00-e8f5-11e8-841b-2c00da50e1ea.png)
![image](https://user-images.githubusercontent.com/45043004/48563697-2c242d00-e8f5-11e8-87ad-efcce9677802.png)
![image](https://user-images.githubusercontent.com/45043004/48563736-4231ed80-e8f5-11e8-880e-a53e31dc06a8.png)
![image](https://user-images.githubusercontent.com/45043004/48563764-54139080-e8f5-11e8-9557-75a57a61bfeb.png)
delete a match give java error
reload seem work but nothing more

**Comment by DavidatorusF** [comment]
still 2 mistakes

I get error java when I choose
-show my leagues matches
-show my cup matches

error java for cup matches :+1: java.lang.NullPointerException
 at core.db.MatchesOverviewQuery.fillMatchesOverviewChanceRow(MatchesOverviewQuery.java:156)
 at core.db.MatchesOverviewQuery.getChancesStat(MatchesOverviewQuery.java:134)
 at core.db.DBManager.getChancesStat(DBManager.java:1253)
 at module.matches.statistics.MatchesHighlightsTable.getValues(MatchesHighlightsTable.java:37)
 at module.matches.statistics.MatchesHighlightsTable.refresh(MatchesHighlightsTable.java:50)
 at module.matches.SpielePanel.doReInit(SpielePanel.java:413)
 at module.matches.SpielePanel.access$600(SpielePanel.java:61)
 at module.matches.SpielePanel$8.itemStateChanged(SpielePanel.java:199)
 at javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1223)
 at javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1280)
 at javax.swing.JComboBox.contentsChanged(JComboBox.java:1330)
 at javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:118)
 at javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:93)
 at javax.swing.JComboBox.setSelectedItem(JComboBox.java:576)
 at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:622)
 at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:868)
 at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
 at java.awt.Component.processMouseEvent(Component.java:6539)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(BasicComboPopup.java:517)
 at java.awt.Component.processEvent(Component.java:6304)
 at java.awt.Container.processEvent(Container.java:2239)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2297)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
 at java.awt.Container.dispatchEventImpl(Container.java:2283)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
 at java.awt.EventQueue$4.run(EventQueue.java:733)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
