### ISSUE TITLE
No deja cargar hattrick organizer, da error de java.lang.stackOverflowError 

### ISSUE THREAD

**Issue by homersito1979** [akasolace/HO#1606]
va.lang.StackOverflowError
	at java.desktop/sun.awt.image.BufImgSurfaceData.initRaster(Native Method)
	at java.desktop/sun.awt.image.BufImgSurfaceData.createDataIC(BufImgSurfaceData.java:274)
	at java.desktop/sun.awt.image.BufImgSurfaceData.createData(BufImgSurfaceData.java:95)
	at java.desktop/sun.awt.image.VolatileSurfaceManager.getBackupSurface(VolatileSurfaceManager.java:284)
	at java.desktop/sun.awt.image.VolatileSurfaceManager.initialize(VolatileSurfaceManager.java:134)
	at java.desktop/sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:93)
	at java.desktop/sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:122)
	at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:305)
	at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:239)
	at java.desktop/javax.swing.plaf.nimbus.AbstractRegionPainter.getImage(AbstractRegionPainter.java:713)
	at java.desktop/javax.swing.plaf.nimbus.AbstractRegionPainter.paintWith9SquareCaching(AbstractRegionPainter.java:645)
	at java.desktop/javax.swing.plaf.nimbus.AbstractRegionPainter.paint(AbstractRegionPainter.java:160)
	at java.desktop/javax.swing.plaf.nimbus.AbstractRegionPainter.paint(AbstractRegionPainter.java:43)
	at java.desktop/javax.swing.plaf.nimbus.SynthPainterImpl.paint(SynthPainterImpl.java:61)
	at java.desktop/javax.swing.plaf.nimbus.SynthPainterImpl.paintBackground(SynthPainterImpl.java:102)
	at java.desktop/javax.swing.plaf.nimbus.SynthPainterImpl.paintTextFieldBackground(SynthPainterImpl.java:2350)
	at java.desktop/javax.swing.plaf.synth.SynthTextFieldUI.paintBackground(SynthTextFieldUI.java:201)
	at java.desktop/javax.swing.plaf.synth.SynthTextFieldUI.update(SynthTextFieldUI.java:180)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:797)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at core.gui.comp.panel.ImagePanel.paint(ImagePanel.java:52)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1618)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5025)
	at core.gui.InfoPanel.paintComponentImmediately(InfoPanel.java:90)
	at core.gui.InfoPanel.setInformation(InfoPanel.java:62)
	at core.gui.InfoPanel.setInformation(InfoPanel.java:69)
	at core.gui.InfoPanel.setInformation(InfoPanel.java:53)
	at core.gui.HOMainFrame.setInformation(HOMainFrame.java:246)
	at core.gui.HOMainFrame.setWaitInformation(HOMainFrame.java:242)
	at core.net.OnlineWorker.showWaitInformation(OnlineWorker.java:755)
	at core.net.OnlineWorker.downloadMatchDetails(OnlineWorker.java:878)
	at core.net.OnlineWorker.downloadMatchData(OnlineWorker.java:282)
	at core.net.OnlineWorker.downloadMatchData(OnlineWorker.java:247)
	at core.model.match.Matchdetails.getHighlights(Matchdetails.java:992)
	at core.file.xml.XMLMatchdetailsParser.parseMatchReport(XMLMatchdetailsParser.java:505)
	at core.file.xml.XMLMatchdetailsParser.createMatchdetails(XMLMatchdetailsParser.java:51)
	at core.file.xml.XMLMatchdetailsParser.parseMatchdetailsFromString(XMLMatchdetailsParser.java:32)
	at core.net.OnlineWorker.downloadMatchDetails(OnlineWorker.java:879)
	at core.net.OnlineWorker.downloadMatchData(OnlineWorker.java:365)
	at core.net.OnlineWorker.downloadMatchData(OnlineWorker.java:247)
	at core.model.match.Matchdetails.getHighlights(Matchdetails.java:992)
	at core.file.xml.XMLMatchdetailsParser.parseMatchReport(XMLMatchdetailsParser.java:505)
	at core.file.xml.XMLMatchdetailsParser.createMatchdetails(XMLMatchdetailsParser.java:51)
	.
.
.
..
.

..
.
.
.

**Comment by wsbrenk** [comment]
same as #1586
