### ISSUE TITLE
[BUG] Problem starting HO-6.0.359.1-unix-BETA-JRE.sh

### ISSUE THREAD

**Issue by filex100** [akasolace/HO#1607]
**Describe the bug**
When installing the latest beta, I get an error at startup.

java.lang.NullPointerException: Cannot invoke "java.util.ResourceBundle.containsKey(String)" because "bundle" is null
	at module.lineup.LineupSettingsPanel.getPredictionItems(LineupSettingsPanel.java:499)
	at module.lineup.LineupSettingsPanel.initComponents(LineupSettingsPanel.java:460)
	at module.lineup.LineupSettingsPanel.<init>(LineupSettingsPanel.java:142)
	at module.lineup.LineupRatingAssistantPanel.getLineupSettingsPanel(LineupRatingAssistantPanel.java:39)
	at module.lineup.LineupRatingAssistantPanel.initComponents(LineupRatingAssistantPanel.java:66)
	at module.lineup.LineupRatingAssistantPanel.<init>(LineupRatingAssistantPanel.java:60)
	at module.lineup.LineupPanel.getLineupRatingAssistantPanel(LineupPanel.java:139)
	at module.lineup.LineupPanel.initComponents(LineupPanel.java:117)
	at module.lineup.LineupPanel.<init>(LineupPanel.java:43)
	at module.lineup.LineupMasterView.initComponents(LineupMasterView.java:51)
	at module.lineup.LineupMasterView.<init>(LineupMasterView.java:39)
	at module.lineup.LineupModule.createTabPanel(LineupModule.java:29)
	at core.gui.comp.tabbedPane.HOTabbedPane.showTab(HOTabbedPane.java:38)
	at core.gui.HOMainFrame.initComponents(HOMainFrame.java:445)
	at core.gui.HOMainFrame.<init>(HOMainFrame.java:153)
	at core.gui.HOMainFrame.instance(HOMainFrame.java:214)
	at core.HO.lambda$main$2(HO.java:215)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Platform information:**
 - OS: [Linux ]
 -  Linux Mint 20.3 Una (XFCE)

[HO-2022-07-28.log](https://github.com/akasolace/HO/files/9215245/HO-2022-07-28.log)
[error.log](https://github.com/akasolace/HO/files/9215246/error.log)

**20:38:38 [Error]   core.model.HOVerwaltung: java.util.MissingResourceException: Can't find bundle for base name sprache.Spanish_sudamericano, locale es_CL**

**Same problem in HO-7.0.360.0-unix-DEV-JRE.sh**

Additional data to make it work and fix the problem manually:

--> Install stable version
--> Change language to English
--> Install latest Beta and change the language to spanish.

Now it works fine.

Additional step: take one aspirin.

**Comment by wsbrenk** [comment]
should be fixed in 361

reason was renaming spanish_sudamericano to spanish(AR)
