### ISSUE TITLE
[BUG]setSelectedIndex: 25 out of bounds

### ISSUE THREAD

**Issue by cheilson** [akasolace/HO#1638]
**Describe the bug**
When I try to simulate under team analyzer, this error message comes
**To Reproduce**
1. Go to Team Analyzer
2. Click on Analyze then simulate
3. See error

java.lang.IllegalArgumentException: setSelectedIndex: 25 out of bounds
	at java.desktop/javax.swing.JComboBox.setSelectedIndex(JComboBox.java:652)
	at core.prediction.TeamRatingPanel.addLine(TeamRatingPanel.java:197)
	at core.prediction.TeamRatingPanel.<init>(TeamRatingPanel.java:60)
	at core.prediction.MatchEnginePanel.<init>(MatchEnginePanel.java:52)
	at module.teamAnalyzer.ui.controller.SimButtonListener.actionPerformed(SimButtonListener.java:107)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Screenshots**

![err](https://user-images.githubusercontent.com/52073695/191737187-dddf8fb6-388b-4f58-ac7d-6ff67990ee94.png)

**Platform information:**
Udgave	Windows 11 Home
Version	22H2
Installeret d.	‎21-‎09-‎2022
Operativsystemets build	22621.521
Visning	Windows Feature Experience Pack 1000.22634.1000.0

**Additional context**

**Comment by cheilson** [comment]
Forgot

HO 6.1 beta r371

**Comment by cheilson** [comment]
Problem occured every day until after the weekend match. I downloaded again, and the problem is gone.

It is not the first time I have had issues with that specific team, none of the other 3 have had issues.

Aces Full Revived (2061838)

Maybe it has something to do with that specific team?
