### ISSUE TITLE
[FEATURE] Transfers tab - adding age with transfers

### ISSUE THREAD

**Issue by masterpatje** [akasolace/HO#1659]
Age information is available in hattrick, but is not available in HO on the transfer tab.

The age is important for me to determine value change and for future transfers to look back at choice I made.
![image](https://user-images.githubusercontent.com/102049050/194749738-f15ed602-0350-4a16-a3db-feb7674161f3.png)

Extra option could be to also add a counter with the age difference (like with the other stats); example 33 +9 
![image](https://user-images.githubusercontent.com/102049050/194749891-5b614350-6133-4d51-9aed-bbd9cbf950bc.png)

Beta version: 6.1.371

**Comment by masterpatje** [comment]
Yes, age is included. For some players the age isn't calculated and results in an error:

![image](https://user-images.githubusercontent.com/102049050/203973462-e3706bee-4ca5-4509-9a0d-5335d96a72c5.png)

java.lang.NullPointerException: Cannot invoke "core.model.player.Player.getAgeWithDaysAsString(core.util.HODateTime)" because the return value of "module.transfer.PlayerTransfer.getPlayerInfo()" is null
	at module.transfer.history.PlayerTransferTableModel.getValueAt(PlayerTransferTableModel.java:84)
	at module.transfer.ui.sorter.AbstractTableSorter.getValueAt(AbstractTableSorter.java:223)
	at java.desktop/javax.swing.JTable.getValueAt(JTable.java:2763)
	at java.desktop/javax.swing.JTable.prepareRenderer(JTable.java:5780)
	at java.desktop/javax.swing.plaf.synth.SynthTableUI.paintCell(SynthTableUI.java:688)
	at java.desktop/javax.swing.plaf.synth.SynthTableUI.paintCells(SynthTableUI.java:585)
	at java.desktop/javax.swing.plaf.synth.SynthTableUI.paint(SynthTableUI.java:369)
	at java.desktop/javax.swing.plaf.synth.SynthTableUI.update(SynthTableUI.java:282)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:842)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JSplitPane.paintChildren(JSplitPane.java:1030)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5311)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1657)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1632)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1570)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5259)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5069)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:879)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
