### ISSUE TITLE
Upload de escalação termina com erro

### ISSUE THREAD

**Issue by fjrn200** [akasolace/HO#1667]
java.lang.RuntimeException: CHPP Erro - 6 - This action requires the logged in user to be a Supporter (6) Additional Info: Action type setmatchorder is only available for Hattrick Supporters
	at core.net.MyConnector.uploadMatchOrder(MyConnector.java:389)
	at core.net.OnlineWorker.uploadMatchOrder(OnlineWorker.java:732)
	at module.lineup.lineup.MatchAndLineupSelectionPanel.uploadLineupToHT(MatchAndLineupSelectionPanel.java:369)
	at module.lineup.lineup.MatchAndLineupSelectionPanel.lambda$addListeners$1(MatchAndLineupSelectionPanel.java:194)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by fjrn200** [comment]
java.lang.RuntimeException: CHPP Erro - 6 - This action requires the logged in user to be a Supporter (6) Additional Info: Action type setmatchorder is only available for Hattrick Supporters
	at core.net.MyConnector.uploadMatchOrder(MyConnector.java:389)
	at core.net.OnlineWorker.uploadMatchOrder(OnlineWorker.java:732)
	at module.lineup.lineup.MatchAndLineupSelectionPanel.uploadLineupToHT(MatchAndLineupSelectionPanel.java:369)
	at module.lineup.lineup.MatchAndLineupSelectionPanel.lambda$addListeners$1(MatchAndLineupSelectionPanel.java:194)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by wsbrenk** [comment]
@fjrn200 Is it true that the log claims you are not a supporter?

**Comment by fjrn200** [comment]
@wsbrenk, Eu não sei analisar um log. Então eu não entendo a sua pergunta "você não é um apoiador?" O que eu tenho que apoiar ? O que eu não estou apoiando, o que eu devo fazer ?
Eu uso o Hattrick a bastante tempo e uso também o HO a bastante tempo.
Eu tive que desinstalar o HO no meu PC e então instalei a versão 6.1.384.
Após reinstalar fiz o download normalmente de todas as informações (desde maio de 2020). Mas quando fiz upload da escalação este problema ocorreu.
Por favor, você pode me orientar o que eu devo corrigir ou apoiar para usar o HO corretamente ?
O que eu devo alterar ou corrigir no meu PC ?

**Comment by wsbrenk** [comment]
@fjrn200 the error log you presented says that you not or no longer a hattrick supporter. without supporter you are not allowed to upload match orders. that is what the message is telling us.

If the upload worked with a previous version, it could be due to the following reasons:
* you were hattrick supporter then
* the new ho has an error that causes this error message

what I wanted to improve would be a more understandable error display for the user

**Comment by fjrn200** [comment]
Obrigado por sua ajuda. 
Gostaria de passar a você algumas informações de meu time neste momento: 
Time criado em maio de 2020. Neste momento esta é a situação do time:
2º na V.202   (Team ID=1662397)
Invicto há 9 partidas oficiais

2 343 membros
Estádio: Monumental Stadium capacidade 50 000)

Por motivos particulares, eu fiquei algum tempo sem acessar o Hattrick. Mas no retorno me pareceu tudo normal. Talvez eu possa fazer uma solicitação aos GMs no Hattrick para verificar se está tudo correto o meu time, você recomenda esta ação ?
Obrigado novamente.

**Comment by wsbrenk** [comment]
@fjrn200 is this problem still there?
