### ISSUE TITLE
[BUG] No future training

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1684]
feedback from HT: [Stier32](https://www88.hattrick.org/Club/Manager/?userId=427316&browseIds=) Supporter Platinum
[Open Air](https://www88.hattrick.org/Club/?TeamID=168264)
Schweiz [VI.941](https://www88.hattrick.org/World/Series/?LeagueLevelUnitID=21493):

I have two problems with my oldest team on HO 6.

First problem:
On the Training tab, I don't see any future training and can't add it.
On the training / prediction tab I receive an error (have to put it in two postings)

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.base/java.util.Objects.checkIndex(Objects.java:359)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at module.training.ui.renderer.TrainingRecapRenderer.getTableCellRendererComponent(TrainingRecapRenderer.java:57)
at com.github.weisj.darklaf.ui.table.renderer.DarkTableCellRendererDelegate.getTableCellRendererComponent(DarkTableCellRendererDelegate.java:69)
at java.desktop/javax.swing.JTable.prepareRenderer(JTable.java:5797)
at com.github.weisj.darklaf.ui.table.DarkTableUI.paintCell(DarkTableUI.java:518)
at com.github.weisj.darklaf.ui.table.DarkTableUIBridge.paintCells(DarkTableUIBridge.java:207)
at com.github.weisj.darklaf.ui.table.DarkTableUIBridge.paint(DarkTableUIBridge.java:134)
at com.github.weisj.darklaf.ui.table.DarkTableUI.paint(DarkTableUI.java:453)
at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:842)
at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)

The second problem is on *Int. Friendly Analizer"

I also receive an error:
java.lang.NullPointerException: Cannot invoke "core.model.WorldDetailLeague.getCountryId()" because the return value of "core.model.WorldDetailsManager.getWorldDetailLeagueByLeagueId(java.lang.Integer)" is null

(Can't put in the code, bc HT is thinking of bad scripts....)

**Comment by wsbrenk** [comment]
i fear these errors are the result of another error which destroyed the database.
