### ISSUE TITLE
[BUG] ArrayIndexOutOfBoundsException upon startup of fresh installation

### ISSUE THREAD

**Issue by tychobrailleur** [akasolace/HO#1757]
**Describe the bug**
With `HEAD` from `master`, the following exception occurs when starting the app from scratch:

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at core.gui.comp.table.HOTableModel.getValueAt(HOTableModel.java:172)
	at core.gui.comp.table.HOTableModel.getColumnClass(HOTableModel.java:190)
	at core.gui.comp.table.TableMap.getColumnClass(TableMap.java:28)
	at core.gui.model.ReduzedTableModel.getColumnClass(ReduzedTableModel.java:30)
	at java.desktop/javax.swing.JTable.getColumnClass(JTable.java:2744)
	at java.desktop/javax.swing.JTable.getCellRenderer(JTable.java:5763)
	at java.desktop/javax.swing.plaf.synth.SynthTableUI.paintCell(SynthTableUI.java:687)
	at java.desktop/javax.swing.plaf.synth.SynthTableUI.paintCells(SynthTableUI.java:585)
	at java.desktop/javax.swing.plaf.synth.SynthTableUI.paint(SynthTableUI.java:369)
	at java.desktop/javax.swing.plaf.synth.SynthTableUI.update(SynthTableUI.java:282)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:842)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JSplitPane.paintChildren(JSplitPane.java:1030)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JSplitPane.paintChildren(JSplitPane.java:1030)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at core.gui.comp.panel.ImagePanel.paint(ImagePanel.java:52)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5318)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1105)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:75)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:112)
	at java.desktop/java.awt.Container.paint(Container.java:2005)
	at java.desktop/java.awt.Window.paint(Window.java:3959)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:890)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**To Reproduce**
1. Checkout latest code from `master`
2. Ensure `db` folder is not present
3. Observe exception occurring

**Screenshots**
N/A

**Platform information:**
 - OS: Linux
 - Version Manjaro

**Additional context**

**Comment by tychobrailleur** [comment]
Debugging this, this means to be caused by the Squad table, and no `UserColumn` being selected for display (they are all display `false`), so the data model contains a list of empty objects, causing the error above.

By default we should provide a list of `UserColumn`s to display to avoid this blow up.

**Comment by wsbrenk** [comment]
@tychobrailleur i fear that i introduced this error with this changes: #1749

**Comment by tychobrailleur** [comment]
> @tychobrailleur i fear that i introduced this error with this changes: #1749

Ah cool!!! Super helpful, yes that looks like it.  That saves a lot of time, thanks!

**Comment by wsbrenk** [comment]
As i was working on #1749 i had the idea to add a new column "isDisplay" to UserColumn table. maybe this makes it easier to handle both cases:
* very first start of HO
* restart after user has disabled a column in settings

**Comment by tychobrailleur** [comment]
@wsbrenk What release notes / changelog have to be changed these days?

**Comment by wsbrenk** [comment]
@tychobrailleur  only this one : src/main/resources/release_notes.md

**Comment by tychobrailleur** [comment]
Perfect, thanks.  PR to follow!

**Comment by wsbrenk** [comment]
@tychobrailleur  what about userCanDisableColumns() in PlayerAnalysisModel - does that need also a fix?

**Comment by tychobrailleur** [comment]
> @tychobrailleur what about userCanDisableColumns() in PlayerAnalysisModel - does that need also a fix?

I haven't seen that one blow up, but I can certainly add the same fix to it.

**Comment by tychobrailleur** [comment]
> @tychobrailleur what about userCanDisableColumns() in PlayerAnalysisModel - does that need also a fix?

Done.

**Comment by tychobrailleur** [comment]
There seems to be a situation where this still happens, in particular when going from Squad --> Lineup tab, but not the other way around.

**Comment by tychobrailleur** [comment]
Yeah, that column display false is messing a few things up: in some situations, the list of displayed columns is completely empty.  Then adding back all of them adds “Name” in the main table (as well as the first fixed column).  Removing it puts the Jersey number in the first fixed column, the name no longer appears.  We'll have to think more about that #1749 fix.

**Comment by wsbrenk** [comment]
I vote for the isDisplayed column

**Comment by wsbrenk** [comment]
or even better isDisabled 
* true -> do not display column
* null or false -> display the column

=> no great database migration is necessary

**Comment by tychobrailleur** [comment]
I think Name should not be "disableable" in any case.

**Comment by tychobrailleur** [comment]
Finally tracked down this issue, cf. #1768...  The key change is that Name and ID should never be edited/removed from the table, which makes sense because it doesn't make sense to have a list of entries without either.
