### ISSUE TITLE
[BUG] NPE when loading old HRF files

### ISSUE THREAD

**Issue by tychobrailleur** [akasolace/HO#1766]
**Describe the bug**
When loading old HRF Files, the following errors appear in the log file:

```
Xlib: sequence lost (0xb0000 > 0xae93f) in reply type 0x2!
Xlib: sequence lost (0xb0000 > 0xae9b9) in reply type 0x3!
 [Error]   MyConnector: CHPP Error - 56 -  (56) Additional Info: null
java.lang.RuntimeException: CHPP Error - 56 -  (56) Additional Info: null
	at core.net.MyConnector.getCHPPWebFile(MyConnector.java:671)
	at core.net.MyConnector.downloadPlayerDetails(MyConnector.java:467)
	at core.net.OnlineWorker.downloadPlayerDetails(OnlineWorker.java:1216)
	at core.model.player.Player.<init>(Player.java:471)
	at core.file.hrf.HRFStringParser.createHOModel(HRFStringParser.java:193)
	at core.file.hrf.HRFStringParser.parse(HRFStringParser.java:132)
	at core.file.hrf.HRFFileParser.parse(HRFFileParser.java:27)
	at core.file.hrf.HRFImport.<init>(HRFImport.java:50)
	at core.gui.HOMainFrame.actionPerformed(HOMainFrame.java:309)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Xlib: sequence lost (0xb0000 > 0xaee6f) in reply type 0x2!
Xlib: sequence lost (0xb0000 > 0xaeeea) in reply type 0x3!
 [Error]   HRFStringParser: Cannot invoke "org.w3c.dom.Document.getDocumentElement()" because "doc" is null
java.lang.NullPointerException: Cannot invoke "org.w3c.dom.Document.getDocumentElement()" because "doc" is null
	at core.file.xml.XMLPlayersParser.parsePlayerDetailsFromString(XMLPlayersParser.java:351)
	at core.net.OnlineWorker.downloadPlayerDetails(OnlineWorker.java:1217)
	at core.model.player.Player.<init>(Player.java:471)
	at core.file.hrf.HRFStringParser.createHOModel(HRFStringParser.java:193)
	at core.file.hrf.HRFStringParser.parse(HRFStringParser.java:132)
	at core.file.hrf.HRFFileParser.parse(HRFFileParser.java:27)
	at core.file.hrf.HRFImport.<init>(HRFImport.java:50)
	at core.gui.HOMainFrame.actionPerformed(HOMainFrame.java:309)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Xlib: sequence lost (0xb0000 > 0xaf36f) in reply type 0x2!
Xlib: sequence lost (0xb0000 > 0xaf3e9) in reply type 0x3!
 [Error]   MyConnector: CHPP Error - 56 -  (56) Additional Info: null
java.lang.RuntimeException: CHPP Error - 56 -  (56) Additional Info: null
	at core.net.MyConnector.getCHPPWebFile(MyConnector.java:671)
	at core.net.MyConnector.downloadPlayerDetails(MyConnector.java:467)
	at core.net.OnlineWorker.downloadPlayerDetails(OnlineWorker.java:1216)
	at core.model.player.Player.<init>(Player.java:471)
	at core.file.hrf.HRFStringParser.createHOModel(HRFStringParser.java:193)
	at core.file.hrf.HRFStringParser.parse(HRFStringParser.java:132)
	at core.file.hrf.HRFFileParser.parse(HRFFileParser.java:27)
	at core.file.hrf.HRFImport.<init>(HRFImport.java:50)
	at core.gui.HOMainFrame.actionPerformed(HOMainFrame.java:309)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Xlib: sequence lost (0xb0000 > 0xaf89e) in reply type 0x2!
Xlib: sequence lost (0xb0000 > 0xaf918) in reply type 0x3!
 [Error]   HRFStringParser: Cannot invoke "org.w3c.dom.Document.getDocumentElement()" because "doc" is null
java.lang.NullPointerException: Cannot invoke "org.w3c.dom.Document.getDocumentElement()" because "doc" is null
	at core.file.xml.XMLPlayersParser.parsePlayerDetailsFromString(XMLPlayersParser.java:351)
	at core.net.OnlineWorker.downloadPlayerDetails(OnlineWorker.java:1217)
	at core.model.player.Player.<init>(Player.java:471)
	at core.file.hrf.HRFStringParser.createHOModel(HRFStringParser.java:193)
	at core.file.hrf.HRFStringParser.parse(HRFStringParser.java:132)
	at core.file.hrf.HRFFileParser.parse(HRFFileParser.java:27)
	at core.file.hrf.HRFImport.<init>(HRFImport.java:50)
	at core.gui.HOMainFrame.actionPerformed(HOMainFrame.java:309)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**To Reproduce**
1. Clear DB
2. Start HO from HEAD in master
3. Load old HRF Files
4. Observe errors

**Screenshots**
![Screenshot from 2022-12-28 12-25-19](https://user-images.githubusercontent.com/114285/209812024-cf72c26b-f090-4456-ab6f-0822ba04a0b4.png)
![Screenshot from 2022-12-28 12-24-41](https://user-images.githubusercontent.com/114285/209812028-96b0b246-8a89-4b2d-b987-5e30abfd9407.png)

**Platform information:**
 - OS: Linux
 - Version Manjaro 22.0

**Additional context**
N/A

**Comment by wsbrenk** [comment]
it was probably not a good idea to start a download in the constructor of Player.

Player Dean Mahler is in your Hall of Fame: 
~~~
<?xml version="1.0" encoding="utf-8"?>
<HattrickData>
  <FileName>chpperror.xml</FileName>
  <Version>1.1</Version>
  <UserID>1757369</UserID>
  <FetchedDate>2022-12-28 18:04:03</FetchedDate>
  <Error> (56) Additional Info: null</Error>
  <ErrorCode>56</ErrorCode>
  <ErrorGUID>f71edb6a-962c-479f-b6f1-dd814062e5d1</ErrorGUID>
  <Server>chpp83.hattrick.org</Server>
  <Request>/chppxml.ashx?file=playerdetails&amp;version=2.9&amp;actionType=view&amp;playerID=446958676&amp;=&amp;oauth_token=GIBXwjS3iXIHfmnW&amp;oauth_nonce=6b62997f-2e58-40f4-8b90-b59a36472f06&amp;oauth_consumer_key=zcLBKUMmM2D6iCJofw9hfr&amp;oauth_signature_method=HMAC-SHA1&amp;oauth_timestamp=1672247043&amp;oauth_version=1.0&amp;oauth_signature=%2BhXrpS8NtPL53pzSJsPqMXxmxR8%3D</Request>
  <LineNumber>91</LineNumber>
</HattrickData>
~~~

**Comment by wsbrenk** [comment]
I assume that in this context the mother club info is not needed at all. Then moving the download to the getter might help. including a correct error handling.

**Comment by tychobrailleur** [comment]
> Player Dean Mahler is in your Hall of Fame:

Ah yes, good old Dean, I moved him today to the HoF. ;-)  He will be missed!
