### ISSUE TITLE
Cannot invoke nextTrainingDate - null pointer (core.model.XtraData)

### ISSUE THREAD

**Issue by frutak** [akasolace/HO#1779]
Hey,

I have been updating HO around the time of the Great Crash and I am struggling through future training dates not being populated. I noticed one of the DEV commits addressing this issue, but if I try the DEV release (I tried few latest once) I get the error already on startup of HO (the GUI doesnt show) while with stable and BETA I only get the exception when opening the Training tab.

Can you think of any quick fix for this, or do I just need to wait for a new release?

Thanks for your contributions, the  tool is great and I really appreciate the work that you are puttting into it.

regards,
frutak

**Comment by wsbrenk** [comment]
#1780  will be fixed in a few minutes - please try again with .456 if it is ready

**Comment by frutak** [comment]
Thanks for your support. I tried the 456 and I still get the exception on startup.

full exception stack trace:
java.lang.NullPointerException: Cannot invoke "core.model.XtraData.getNextTrainingDate()" because the return value of "core.model.HOModel.getXtraDaten()" is null
	at core.util.HODateTime.toTrainingWeek(HODateTime.java:291)
	at module.playerOverview.SpielerTrainingsVergleichsPanel.loadCBItemHRFList(SpielerTrainingsVergleichsPanel.java:181)
	at module.playerOverview.SpielerTrainingsVergleichsPanel.loadHRFListe(SpielerTrainingsVergleichsPanel.java:200)
	at module.playerOverview.SpielerTrainingsVergleichsPanel.<init>(SpielerTrainingsVergleichsPanel.java:54)
	at module.playerOverview.SpielerUebersichtsPanel.initSpielerHistory(SpielerUebersichtsPanel.java:144)
	at module.playerOverview.SpielerUebersichtsPanel.initComponents(SpielerUebersichtsPanel.java:103)
	at module.playerOverview.SpielerUebersichtsPanel.<init>(SpielerUebersichtsPanel.java:35)
	at module.playerOverview.PlayerOverviewModule.createTabPanel(PlayerOverviewModule.java:30)
	at core.gui.comp.tabbedPane.HOTabbedPane.showTab(HOTabbedPane.java:38)
	at core.gui.HOMainFrame.initComponents(HOMainFrame.java:448)
	at core.gui.HOMainFrame.<init>(HOMainFrame.java:153)
	at core.gui.HOMainFrame.instance(HOMainFrame.java:215)
	at core.HO.lambda$main$1(HO.java:225)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by wsbrenk** [comment]
@frutak i fear this is from a corrupt database - could you try an older backup which hopefully is not corrupt?

what happens if you start from scratch (with a new database)?

**Comment by frutak** [comment]
you were right - after dropping the db all features worked. I must have gotten an inconsistent dataset around the Great Crash

I have reloaded everything from hrfs, things seem to be running fine. Thanks for your support!
