### ISSUE TITLE
[BUG] NPE when starting HO

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1780]
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "core.model.player.Player.getLastMatchId()" is null
	at core.gui.model.UserColumnFactory$35.getTableEntry(UserColumnFactory.java:735)
	at core.gui.model.PlayerOverviewModel.initData(PlayerOverviewModel.java:166)
	at core.gui.model.PlayerOverviewModel.setValues(PlayerOverviewModel.java:106)
	at module.playerOverview.PlayerOverviewTable.initModel(PlayerOverviewTable.java:161)
	at module.playerOverview.PlayerOverviewTable.<init>(PlayerOverviewTable.java:51)
	at module.playerOverview.SpielerUebersichtsPanel.initPlayersTable(SpielerUebersichtsPanel.java:168)
	at module.playerOverview.SpielerUebersichtsPanel.initComponents(SpielerUebersichtsPanel.java:100)
	at module.playerOverview.SpielerUebersichtsPanel.<init>(SpielerUebersichtsPanel.java:35)
	at module.playerOverview.PlayerOverviewModule.createTabPanel(PlayerOverviewModule.java:30)
	at core.gui.comp.tabbedPane.HOTabbedPane.showTab(HOTabbedPane.java:38)
	at core.gui.HOMainFrame.initComponents(HOMainFrame.java:448)
	at core.gui.HOMainFrame.<init>(HOMainFrame.java:153)
	at core.gui.HOMainFrame.instance(HOMainFrame.java:215)
	at core.HO.lambda$main$1(HO.java:225)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)

**Comment by wsbrenk** [comment]
error happens if there are players in the team without any (last) match
