### ISSUE TITLE
[FEATURE] National Team Prospects View & Lineup Bug Fix

### ISSUE THREAD

**Issue by Achill-3s** [akasolace/HO#1832]
**Is your feature request related to a problem? Please describe.**
As a National Coach, I can only see my selected lineup.
It would be much more useful to be able to see the 150 NT Prospects which are selected into a different tab.
![image](https://user-images.githubusercontent.com/98124706/226099960-f199c2c3-46a5-4c46-a46d-001ba174a8d1.png)

**Describe the solution you'd like**
Create new Tab called 'NT Prospects'.
Display all selected Prospects in a similar way to the Tab 'Squad'
Allow button to move Prospects from the  'NT Prospects' Tab to the 'Squad' Tab.
This should also automatically update the Prospects in Hattrick side.

**Additional context**
Also there is a bug where when you setup the lineup of the National Team and you try to upload your orders, it gives the error that you cannot do so, because it is not your own team.
It shouldn't gives this error for the National Coach.
![image](https://user-images.githubusercontent.com/98124706/226100201-4c310e21-3dbf-4e73-9bfa-ff3d9e11d518.png)

**Comment by wsbrenk** [comment]
i will try to fix the match order bug first. 

Concerning NT Prospects, i don't know if the required information can be accessed by the chpp api.

**Comment by Achill-3s** [comment]
Let me know if there is any way i can help you out, such as testing etc.

Also the prospects api, only the Hattrick developers will logically know.
So i assume you have a way to contact them for the above or do you want me to try to reach out for them instead?

**Comment by wsbrenk** [comment]
this is from CHPP request list:


Important
- add Prospects and Staff lists for NT teams

**Comment by wsbrenk** [comment]
@Achill-3s newest beta changed the nt match order access. I can't test it by myself.

**Comment by Achill-3s** [comment]
Still pulls an error, a different one this time.
Seems like you have part of code trying to verify if the NT Teamid has me as the owner, instead of the NT Coach.

HO Beta Version - HO-7.0.478.1-portable-win-BETA-JRE
JRE Version - 17.0.3

java.lang.RuntimeException: CHPP Error - 59 -  (59) Additional Info: The supplied teamId does not refer to a senior or youth team managed by the requesting user
	at core.net.MyConnector.uploadMatchOrder(MyConnector.java:359)
	at core.net.OnlineWorker.uploadMatchOrder(OnlineWorker.java:716)
	at module.lineup.lineup.MatchAndLineupSelectionPanel.uploadLineupToHT(MatchAndLineupSelectionPanel.java:369)
	at module.lineup.lineup.MatchAndLineupSelectionPanel.lambda$addListeners$1(MatchAndLineupSelectionPanel.java:194)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

![image](https://user-images.githubusercontent.com/98124706/226142670-5c291177-9ddb-4b66-855c-9ddb61d7c6ba.png)

![image](https://user-images.githubusercontent.com/98124706/226142797-ea9a796f-4efb-4a0b-9a24-2ff37872cadf.png)

**Comment by Achill-3s** [comment]
Hello [wsbrenk],
NT Match Order Issue still persists.

Attaching the file you have requested.
Also check your HT-Mail ingame for info for it.

![image](https://user-images.githubusercontent.com/98124706/226284980-72f5d778-3297-4ac8-be70-fb66694011e9.png)
[cynt.zip](https://github.com/akasolace/HO/files/11015647/cynt.zip)

**Comment by wsbrenk** [comment]
It looks like the lineup for NT Teams is not supported by CHPP. Download did not work today.

**Comment by Achill-3s** [comment]
Please find updated file.
[cynt2.zip](https://github.com/akasolace/HO/files/11163074/cynt2.zip)

**Comment by wsbrenk** [comment]
download of nt prospects is on the chpp feature request list (not available yet in ht).

what could be done in next HO version:
add a feature to import tracker hrfs to an extra prospect panel
