### ISSUE TITLE
[BUG] download fails of substitutions with undocumented goal difference criteria

### ISSUE THREAD

**Issue by Chilimonster** [akasolace/HO#1881]
**Describe the bug**
I have done my usual HO Downloads this evening for my four teams. Three were fine, but one gave a "File is corrupt" error. I deleted the most recent file in the db folder, but still got the same error, so next I removed them all and copied over my recent update from 24 April. The HO database opened ok, but I still get the "File is corrupt" message on attempted data Download.
On the HT forum, wsbrek said "this looks like an parse error of the ht input files."

**To Reproduce**
1. File > Download
2. Error: "File is corrupt"

**Platform information:**
 - OS: Windows
 - Version Windows 10 Home; OS Build 19045.2965

**Additional context**
Issue is with teamID=55248, which is "db" (as opposed to db2, db3, db4) in HO.
Most recent log:
2023-06-07 22:24:40 [Info]    core.HO: VERSION: 7.0   versionType:  RELEASE   RevisionNumber: 494
2023-06-07 22:34:18 [Info]    core.db.backup.HOZip: Create Backup: C:\Users\Kevin\AppData\Roaming\HO\db3\db_Fly Suckers-2023-06-07.zip
2023-06-07 22:36:44 [Info]    core.db.DBManager: instance jdbc:hsqldb:file:C:\Users\Kevin\AppData\Roaming\HO\db2/database; parent folder: C:\Users\Kevin\AppData\Roaming/HO
2023-06-07 22:36:45 [Info]    core.model.HOVerwaltung: language used for interface is: English
2023-06-07 22:36:48 [Info]    core.training.TrainingWeekManager: Next week training date: 2023-06-08 17:15:00
2023-06-07 22:36:48 [Info]    core.gui.HOMainFrame: This is HO! version 7.0, have fun!
2023-06-07 22:36:48 [Info]    core.gui.HOMainFrame: Operating system found: Windows 10 on amd64 (10.0)
2023-06-07 22:36:48 [Info]    core.gui.HOMainFrame: Using java: 17.0.3 (Eclipse Ad2023-06-07 23:05:01 [Error]   core.file.hrf.HRFStringParser: Cannot invoke "module.lineup.substitution.model.GoalDiffCriteria.getId()" because the return value of "module.lineup.substitution.model.Substitution.getStanding()" is null
java.lang.NullPointerException: Cannot invoke "module.lineup.substitution.model.GoalDiffCriteria.getId()" because the return value of "module.lineup.substitution.model.Substitution.getStanding()" is null
	at core.db.MatchSubstitutionTable.lambda$initColumns$22(MatchSubstitutionTable.java:40)
	at core.db.AbstractTable.lambda$insert$0(AbstractTable.java:112)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at core.db.AbstractTable.insert(AbstractTable.java:113)
	at core.db.AbstractTable.store(AbstractTable.java:99)
	at core.db.MatchSubstitutionTable.storeMatchSubstitutionsByMatchTeam(MatchSubstitutionTable.java:81)
	at core.db.DBManager.storeMatchLineupTeam(DBManager.java:2355)
	at core.model.HOModel.storeLineup(HOModel.java:176)
	at core.file.hrf.HRFStringParser.createHOModel(HRFStringParser.java:176)
	at core.file.hrf.HRFStringParser.parse(HRFStringParser.java:129)
	at core.net.OnlineWorker.getHrf(OnlineWorker.java:97)
	at core.net.DownloadDialog.startDownload(DownloadDialog.java:305)
	at core.net.DownloadDialog.actionPerformed(DownloadDialog.java:87)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Any more information needed?

Thanks

**Comment by wsbrenk** [comment]
@Chilimonster At first glance, it looks like a substitution of your next lineup is causing the problem. Can you tell me the attitudes of your planned substitutions - maybe by HT-Mail, if your opponent should read along here.

**Comment by Chilimonster** [comment]
No worries, I'll put them here:
![image](https://github.com/akasolace/HO/assets/67347390/bf1b87dc-ea66-4d3e-b6bc-1595491c4f4c)

Thanks

**Comment by Chilimonster** [comment]
The issue seems to have resolved itself today. I was able to do the Download update successfully.

I tried because I noticed that the HattrickPort did not update on training day last week, but it did yesterday. Could these issues have been linked?

Thanks

**Comment by wsbrenk** [comment]
the download failed last time because of the 3rd substitution "if not in the lead by more than 2 goals". this condition was not in the chpp api documentation and therefore not implemented by HO. 

the newest 7.1 beta should fix this - so even if you defined such substitutions, the download should succeed.
on the other hand, if your current lineup order does not define such substitution, it shouldn't fail either with HO 7.
