### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Chilimonster** [akasolace/HO#1908]
**Describe the bug**
Error opening HO

**To Reproduce**
1. Startup four HO apps for my four teams.
2. Click on icon for each team in turn
3. Three of the databases open normally and can be updated
4. Get error for one team only:
![image](https://github.com/akasolace/HO/assets/67347390/79b66345-4985-4942-b2cb-627d353ea7d3)

java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at org.hsqldb.jdbc.JDBCResultSet.getString(Unknown Source)
	at org.hsqldb.jdbc.JDBCResultSet.getString(Unknown Source)
	at core.db.ModuleConfigTable.findAll(ModuleConfigTable.java:51)
	at core.db.DBManager.loadModuleConfigs(DBManager.java:1914)
	at core.module.config.ModuleConfig.load(ModuleConfig.java:168)
	at core.module.config.ModuleConfig.instance(ModuleConfig.java:25)
	at module.playeranalysis.PlayerAnalysisModule.initialize(PlayerAnalysisModule.java:23)
	at module.playeranalysis.PlayerAnalysisModule.<init>(PlayerAnalysisModule.java:19)
	at core.module.ModuleManager.initMap(ModuleManager.java:54)
	at core.module.ModuleManager.initialize(ModuleManager.java:68)
	at core.module.ModuleManager.<init>(ModuleManager.java:46)
	at core.module.ModuleManager.instance(ModuleManager.java:41)
	at core.gui.HOMainFrame.initComponents(HOMainFrame.java:445)
	at core.gui.HOMainFrame.<init>(HOMainFrame.java:153)
	at core.gui.HOMainFrame.instance(HOMainFrame.java:215)
	at core.HO.lambda$main$1(HO.java:225)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Platform information:**
 - OS: Windows 10
 - Version 22H2 (OS Build 19045.3324)

**Additional context**
Yesterday this same database would only update if CHPP authorisation was provided each time. Backup was loaded which seemed to work ok until today.

Thanks

**Comment by Chilimonster** [comment]
[db_Fly Suckers-2023-07-28.zip](https://github.com/akasolace/HO/files/12480467/db_Fly.Suckers-2023-07-28.zip)
@wsbrenk  This is the most recent backup that will open. I backed up to this one a couple of days ago, did an update. then the next day it wouldn't open again.

Thanks

**Comment by wsbrenk** [comment]
hmm, with the current version i could start and download without any problem:

![image](https://github.com/akasolace/HO/assets/11821502/d48e27ce-b6e0-4e24-9f45-85b184ebeed2)

**Comment by Chilimonster** [comment]
I was able to download and update the database again last night without any issue. I will check again tonight. If all is well, we may be able to close this one down.

Thanks
