### ISSUE TITLE
Hattrick Organizer 1.434 Simulate after Analyze when sector is higher than Divine

### ISSUE THREAD

**Issue by zigmond** [akasolace/HO#20]
setSelectedindex: 21 out of bounds

java.lang.IllegalArgumentException: setSelectedIndex: 21 out of bounds
	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
	at ho.core.prediction.TeamRatingPanel.addLine(TeamRatingPanel.java:184)
	at ho.core.prediction.TeamRatingPanel.<init>(TeamRatingPanel.java:58)
	at ho.core.prediction.MatchEnginePanel.<init>(MatchEnginePanel.java:48)
	at ho.module.teamAnalyzer.ui.controller.SimButtonListener.actionPerformed(SimButtonListener.java:105)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by akasolace** [comment]
Could you please share with me your db folder as a zip file.
I have no good enough team to simulate divine+ratings :-)

**Comment by zigmond** [comment]
Thanks mate, how do I do that ?

**Comment by zigmond** [comment]
db_singleUser-2018-11-28.zip
<https://drive.google.com/file/d/1US4wKoYXWhe3ijGcYnecoBLmm-NEdu0_/view?usp=drive_web>

**Comment by akasolace** [comment]
perfect thank you

**Comment by zigmond** [comment]
:) glad to help

**Comment by zigmond** [comment]
If you can put  link to download it (from scratch even) with the update.
I have win64 if it helps...

**Comment by akasolace** [comment]
which version are you using now?

**Comment by zigmond** [comment]
I redownloded 1434 r2696 and when I open it I get 

java.lang.ArrayIndexOutOfBoundsException: 8
	at ho.core.gui.comp.entry.SpielerLabelEntry.updateDisplay(SpielerLabelEntry.java:307)
	at ho.core.gui.comp.entry.SpielerLabelEntry.createComponent(SpielerLabelEntry.java:215)
	at ho.core.gui.comp.entry.SpielerLabelEntry.<init>(SpielerLabelEntry.java:67)
	at ho.core.gui.model.UserColumnFactory$14.getTableEntry(UserColumnFactory.java:256)
	at ho.core.gui.model.PlayerOverviewModel.initData(PlayerOverviewModel.java:163)
	at ho.core.gui.model.PlayerOverviewModel.setValues(PlayerOverviewModel.java:89)
	at ho.module.playerOverview.PlayerOverviewTable.initModel(PlayerOverviewTable.java:144)
	at ho.module.playerOverview.PlayerOverviewTable.<init>(PlayerOverviewTable.java:33)
	at ho.module.playerOverview.SpielerUebersichtsPanel.initSpielerTabelle(SpielerUebersichtsPanel.java:182)
	at ho.module.playerOverview.SpielerUebersichtsPanel.initComponents(SpielerUebersichtsPanel.java:121)
	at ho.module.playerOverview.SpielerUebersichtsPanel.<init>(SpielerUebersichtsPanel.java:45)
	at ho.module.playerOverview.PlayerOverviewModule.createTabPanel(PlayerOverviewModule.java:30)
	at ho.core.gui.comp.tabbedPane.HOTabbedPane.showTab(HOTabbedPane.java:38)
	at ho.core.gui.HOMainFrame.initComponents(HOMainFrame.java:473)
	at ho.core.gui.HOMainFrame.<init>(HOMainFrame.java:185)
	at ho.core.gui.HOMainFrame.instance(HOMainFrame.java:279)
	at ho.HO$1.run(HO.java:195)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by zigmond** [comment]
Problem might be that it says win32 as mine is win64

**Comment by akasolace** [comment]
Download and install  HO_1.435-DEV-5_Win32_Installer.exe  from [here]( https://github.com/akasolace/HO/releases)
Be careful with your db  make sure you save it first and put it in HO folder after you insall the new version.
Launch  HO and do updtae HO BETA to get rev6 that fixed your bug !!

**Comment by zigmond** [comment]
ok, fixed the training, but team analyzer won't show any teams at all (usually the teams from my league and other upcoming matches)

**Comment by akasolace** [comment]
I do not use team analyser, but it looks it is a different bug.
Was it working with 1.434?  If yes, please open a new bug report for that specific issue, with as much details as possible (screenshots are good). Thank you
