### ISSUE TITLE
Increase list of supported game (default settings and icons) (e.g. Tournment matches)

### ISSUE THREAD

**Issue by zigmond** [akasolace/HO#21]
I was wondering if there will be an option in the line up tab in venue to have a "Neutral" option as well as Home Away and Derby away, for the purposes of a Tournament match, to help calculate the chances after setting a line up

Thanks :)

**Comment by DavidatorusF** [comment]
neutral for single/ladder/tournament matches already exist : it's away

Coefficient type                  | value
Playing Normal&Away        | 100%
Playing CA                         | 93%
Playing at home                 | 119.892%
Playing derby(away team) | 111.493% •
Playing PIC                        | 83.945%
Playing MOTS                    | 111.49%

source The Unwritten Manual #7

**Comment by akasolace** [comment]
@DavidatorusF,  

What I had in mind is to populate the fied correctly in the lineup when doing tournamant game, setting venue to Away, setting TS and Confidence to normal level ...

What do you think ?

**Comment by DavidatorusF** [comment]
mean a new entry in venue menu : "Tournament"

who, once selected, set the other data by default (TS, confidence,...)

nice idea

**Comment by akasolace** [comment]
@DavidatorusF 

correct this is what I had in mind.

**Comment by akasolace** [comment]
@DavidatorusF  I am almost done implementing this, but just to clarify:
Should those special settings apply to all non official game (e.g. ladder, tournament, single match, ....) ?

**Comment by DavidatorusF** [comment]
ladder, tournament, single match... it's the same rules 

that's the matches who SourceSystem=HTOIntegrated

**Comment by akasolace** [comment]
According to @DavidatorusF, this commit broke the mathes Analyser.
@DavidatorusF, could you tell me how to reproduce that bug? Is it affecting all game or simply tournament game? Thank you

**Comment by DavidatorusF** [comment]
with the same db:
on HO_1.437.0.1058, I can open matches analyser
on HO_2.0.0.1075 I get:

java.lang.ArrayIndexOutOfBoundsException: 18
	at module.matchesanalyzer.data.MatchesAnalyzerMatch.<init>(MatchesAnalyzerMatch.java:70)
	at module.matchesanalyzer.data.MatchesAnalyzerTeam.loadMatches(MatchesAnalyzerTeam.java:99)
	at module.matchesanalyzer.data.MatchesAnalyzerTeam.getMatches(MatchesAnalyzerTeam.java:119)
	at module.matchesanalyzer.ui.MatchesAnalyzerTeamPanel.updateMatchesTable(MatchesAnalyzerTeamPanel.java:198)
	at module.matchesanalyzer.ui.MatchesAnalyzerTeamPanel.<init>(MatchesAnalyzerTeamPanel.java:174)
	at module.matchesanalyzer.ui.MatchesAnalyzerPanel.initialize(MatchesAnalyzerPanel.java:33)
	at core.gui.comp.panel.LazyPanel.callInitialize(LazyPanel.java:150)
	at core.gui.comp.panel.LazyPanel.access$300(LazyPanel.java:16)
	at core.gui.comp.panel.LazyPanel$2.hierarchyChanged(LazyPanel.java:137)
	at java.awt.Component.processHierarchyEvent(Component.java:6706)
	at java.awt.Component.processEvent(Component.java:6325)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.Component.createHierarchyEvents(Component.java:5555)
	at java.awt.Container.createHierarchyEvents(Container.java:1448)
	at java.awt.Component.show(Component.java:1639)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at javax.swing.JComponent.setVisible(JComponent.java:2644)
	at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:394)
	at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270)
	at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132)
	at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67)
	at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616)
	at javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591)
	at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647)
	at javax.swing.plaf.synth.SynthTabbedPaneUI$1.mousePressed(SynthTabbedPaneUI.java:312)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by DavidatorusF** [comment]
**Log from HO_1.437.0.1058**

14:46:24 [Info]    core.gui.HOMainFrame: This is HO! version 1.437 DEV (r1058), have fun!
14:46:24 [Info]    core.gui.HOMainFrame: Operating system found: Linux on amd64 (4.4.0-66-generic)
14:46:24 [Info]    core.gui.HOMainFrame: Using java: 1.8.0_191 (Oracle Corporation)

**Log from HO_2.0.0.1075**

14:50:25 [Info]    core.db.DBUpdater: Development update done, setting db version number from 24 to 24
14:50:26 [Info]    core.gui.HOMainFrame: This is HO! version 2.000 DEV (r1075), have fun!
14:50:26 [Info]    core.gui.HOMainFrame: Operating system found: Linux on amd64 (4.4.0-66-generic)
14:50:26 [Info]    core.gui.HOMainFrame: Using java: 1.8.0_191 (Oracle Corporation)
14:51:46 [Error]   core.util.ExceptionHandler: java.lang.ArrayIndexOutOfBoundsException: 18
14:51:46 [Error]   core.util.ExceptionHandler: module.matchesanalyzer.data.MatchesAnalyzerMatch.<init>(MatchesAnalyzerMatch.java:70)
14:51:46 [Error]   core.util.ExceptionHandler: module.matchesanalyzer.data.MatchesAnalyzerTeam.loadMatches(MatchesAnalyzerTeam.java:99)
14:51:46 [Error]   core.util.ExceptionHandler: module.matchesanalyzer.data.MatchesAnalyzerTeam.getMatches(MatchesAnalyzerTeam.java:119)
14:51:46 [Error]   core.util.ExceptionHandler: module.matchesanalyzer.ui.MatchesAnalyzerTeamPanel.updateMatchesTable(MatchesAnalyzerTeamPanel.java:198)
14:51:46 [Error]   core.util.ExceptionHandler: module.matchesanalyzer.ui.MatchesAnalyzerTeamPanel.<init>(MatchesAnalyzerTeamPanel.java:174)
14:51:46 [Error]   core.util.ExceptionHandler: module.matchesanalyzer.ui.MatchesAnalyzerPanel.initialize(MatchesAnalyzerPanel.java:33)
14:51:46 [Error]   core.util.ExceptionHandler: core.gui.comp.panel.LazyPanel.callInitialize(LazyPanel.java:150)
14:51:46 [Error]   core.util.ExceptionHandler: core.gui.comp.panel.LazyPanel.access$300(LazyPanel.java:16)
14:51:46 [Error]   core.util.ExceptionHandler: core.gui.comp.panel.LazyPanel$2.hierarchyChanged(LazyPanel.java:137)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Component.processHierarchyEvent(Component.java:6706)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Component.processEvent(Component.java:6325)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Container.processEvent(Container.java:2239)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Component.dispatchEventImpl(Component.java:4889)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Container.dispatchEventImpl(Container.java:2297)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Component.dispatchEvent(Component.java:4711)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Component.createHierarchyEvents(Component.java:5555)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Container.createHierarchyEvents(Container.java:1448)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Component.show(Component.java:1639)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Component.show(Component.java:1671)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Component.setVisible(Component.java:1623)
14:51:46 [Error]   core.util.ExceptionHandler: javax.swing.JComponent.setVisible(JComponent.java:2644)
14:51:46 [Error]   core.util.ExceptionHandler: javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:394)
14:51:46 [Error]   core.util.ExceptionHandler: javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270)
14:51:46 [Error]   core.util.ExceptionHandler: javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132)
14:51:46 [Error]   core.util.ExceptionHandler: javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67)
14:51:46 [Error]   core.util.ExceptionHandler: javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616)
14:51:46 [Error]   core.util.ExceptionHandler: javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591)
14:51:46 [Error]   core.util.ExceptionHandler: javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647)
14:51:46 [Error]   core.util.ExceptionHandler: javax.swing.plaf.synth.SynthTabbedPaneUI$1.mousePressed(SynthTabbedPaneUI.java:312)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Component.processMouseEvent(Component.java:6536)
14:51:46 [Error]   core.util.ExceptionHandler: javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Component.processEvent(Component.java:6304)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Container.processEvent(Container.java:2239)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Component.dispatchEventImpl(Component.java:4889)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Container.dispatchEventImpl(Container.java:2297)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Component.dispatchEvent(Component.java:4711)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Container.dispatchEventImpl(Container.java:2283)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Window.dispatchEventImpl(Window.java:2746)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.Component.dispatchEvent(Component.java:4711)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.EventQueue.access$500(EventQueue.java:97)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.EventQueue$3.run(EventQueue.java:709)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.EventQueue$3.run(EventQueue.java:703)
14:51:46 [Error]   core.util.ExceptionHandler: java.security.AccessController.doPrivileged(Native Method)
14:51:46 [Error]   core.util.ExceptionHandler: java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
14:51:46 [Error]   core.util.ExceptionHandler: java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.EventQueue$4.run(EventQueue.java:733)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.EventQueue$4.run(EventQueue.java:731)
14:51:46 [Error]   core.util.ExceptionHandler: java.security.AccessController.doPrivileged(Native Method)
14:51:46 [Error]   core.util.ExceptionHandler: java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
14:51:46 [Error]   core.util.ExceptionHandler: java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by akasolace** [comment]
@brokenelevator ok pretty clear :-)
I will take care of that one
