### ISSUE TITLE
[eBUG] MinuteTogglerPanel crashes when no rating object avaiilable

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#254]
**Describe the bug**
I opened an issue based on the discussion betwee @DavidatorusF and @brokenelevator   on slack. I am not sure I have all the information right.
@brokenelevator  could you please tell me if it something we should/can close before 2.0 ?
@DavidatorusF can you give more details on how to reproduce it? 

thank you

when I click on double arrows from timeline:
java.util.NoSuchElementException
    at java.util.ArrayList$ListItr.previous(ArrayList.java:939)
    at module.lineup.MinuteTogglerPanel.shiftBackward(MinuteTogglerPanel.java:239)
    at module.lineup.MinuteTogglerPanel.access$1000(MinuteTogglerPanel.java:25)
    at module.lineup.MinuteTogglerPanel$4.mousePressed(MinuteTogglerPanel.java:109)
    at java.awt.Component.processMouseEvent(Component.java:6536)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6304)
    at java.awt.Container.processEvent(Container.java:2239)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2297)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
    at java.awt.Container.dispatchEventImpl(Container.java:2283)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
    at java.awt.EventQueue$4.run(EventQueue.java:733)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by DavidatorusF** [comment]
@akasolace just a fresh install for reproduce it

**Comment by akasolace** [comment]
> @akasolace just a fresh install for reproduce it

Fresh install and then what ?

**Comment by DavidatorusF** [comment]
fresh install and get authorisation

timeline don't appear

![image](https://user-images.githubusercontent.com/45043004/66837677-ac1ea100-ef63-11e9-849f-9ff8ad49206f.png)

click on double arrows, you will see error

**Comment by akasolace** [comment]
so
1) fresh install
2) get authorisation
3) download data
4) click on arrow

correct?

**Comment by DavidatorusF** [comment]
right

**Comment by akasolace** [comment]
> right 

> it expects (is built of) the ratings. if there are no ratings there are no minute buttons. if there are no minute buttons you can not shift through them, hence the error.

I understand the remark from @brokenelevator but in this case I don't get what is going on. A rating object should have been created when the download is done. Especially that on the screenshot I can see that there are values in the ratings boxes (those values should also be read from the ratings object)....

> just don't show entire panel if the ratings are not there. By entire I mean, the new things (minute, clock, shift, ET, chart button[s]).

I agree with this approach. Hence I see 2 things to be done here:

1) hide new panel (minute, clock, shift, ET, chart button[s]) if the ratings are not there 

2) understand in which circunstances there are no ratings object but still some rating values being displayed (bug reported by @DavidatorusF after fresh install)

**Comment by akasolace** [comment]
closed by 9c9265302285684e26eff7a8fe9c5ca0e91e815c
