### ISSUE TITLE
[eBUG]npe in team analyzer analyze 

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#418]
java.lang.NullPointerException
	at core.specialevents.PowerfulEventPredictionAnalyzer.getOvercrowding(PowerfulEventPredictionAnalyzer.java:101)
	at core.specialevents.PowerfulEventPredictionAnalyzer.getPowerfulNormalForward(PowerfulEventPredictionAnalyzer.java:119)
	at core.specialevents.PowerfulEventPredictionAnalyzer.analyzePosition(PowerfulEventPredictionAnalyzer.java:47)
	at core.specialevents.SpecialEventsPredictionManager$Analyse.analyzeLineup(SpecialEventsPredictionManager.java:57)
	at core.specialevents.SpecialEventsPredictionManager.analyzeLineup(SpecialEventsPredictionManager.java:208)
	at module.teamAnalyzer.report.TeamReport.addSpecialEvents(TeamReport.java:99)
	at module.teamAnalyzer.report.TeamReport.addMatch(TeamReport.java:88)
	at module.teamAnalyzer.manager.ReportManager.buildReport(ReportManager.java:52)
	at module.teamAnalyzer.manager.ReportManager.updateReport(ReportManager.java:72)
	at module.teamAnalyzer.SystemManager.updateReport(SystemManager.java:181)
	at module.teamAnalyzer.ui.FilterPanel$2.actionPerformed(FilterPanel.java:170)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by akasolace** [comment]
closed by #419
