### ISSUE TITLE
[eBUG]another team analyzer ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#425]
java.lang.ArrayIndexOutOfBoundsException: 8
	at core.model.player.Player.hasSpeciality(Player.java:1311)
	at core.specialevents.UnpredictableEventPredictionAnalyzer.analyzePosition(UnpredictableEventPredictionAnalyzer.java:60)
	at core.specialevents.SpecialEventsPredictionManager$Analyse.analyzeLineup(SpecialEventsPredictionManager.java:57)
	at core.specialevents.SpecialEventsPredictionManager.analyzeLineup(SpecialEventsPredictionManager.java:208)
	at module.teamAnalyzer.report.TeamReport.addSpecialEvents(TeamReport.java:99)
	at module.teamAnalyzer.report.TeamReport.addMatch(TeamReport.java:88)
	at module.teamAnalyzer.manager.ReportManager.buildReport(ReportManager.java:52)
	at module.teamAnalyzer.manager.ReportManager.updateReport(ReportManager.java:72)
	at module.teamAnalyzer.SystemManager.updateReport(SystemManager.java:181)
	at module.teamAnalyzer.ui.FilterPanel$2.actionPerformed(FilterPanel.java:170)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

HO 3.0.r2650

**Comment by wsbrenk** [comment]
happens when the analysis goes through a supporter specialty

**Comment by akasolace** [comment]
@wsbrenk this is link to the work you did on special events, right ?

**Comment by wsbrenk** [comment]
@akasolace yes, the exception happened while evaluating the special events propabilities. but as i wrote in pr comment, it could hapen in other occasions too. everytime ho will display support specialty. but as long as nobody recognize those events, we could limit it to the team analyzer usage of Specialty class.

**Comment by akasolace** [comment]
>  it could hapen in other occasions too. everytime ho will display support specialty.

@wsbrenk can you explain me this as I am not following where else it can happen ...
