### ISSUE TITLE
[eBUG] Matches - error

### ISSUE THREAD

**Issue by heteroping** [akasolace/HO#437]
**Describe the bug**
Erroe when clicking on matches

**To Reproduce**
1. Clicked on Matches

**Screenshots**
java.lang.NullPointerException
	at core.db.MatchesOverviewQuery.fillMatchesOverviewChanceRow(MatchesOverviewQuery.java:164)
	at core.db.MatchesOverviewQuery.getChancesStat(MatchesOverviewQuery.java:142)
	at core.db.DBManager.getChancesStat(DBManager.java:1286)
	at module.matches.statistics.MatchesHighlightsTable.getValues(MatchesHighlightsTable.java:37)
	at module.matches.statistics.MatchesHighlightsTable.initModel(MatchesHighlightsTable.java:30)
	at module.matches.statistics.MatchesHighlightsTable.<init>(MatchesHighlightsTable.java:21)
	at module.matches.SpielePanel.initSpieleTabelle(SpielePanel.java:590)
	at module.matches.SpielePanel.initComponents(SpielePanel.java:452)
	at module.matches.SpielePanel.initialize(SpielePanel.java:113)
	at core.gui.comp.panel.LazyImagePanel.callInitialize(LazyImagePanel.java:145)
	at core.gui.comp.panel.LazyImagePanel.access$300(LazyImagePanel.java:13)
	at core.gui.comp.panel.LazyImagePanel$2.hierarchyChanged(LazyImagePanel.java:132)
	at java.awt.Component.processHierarchyEvent(Component.java:6706)
	at java.awt.Component.processEvent(Component.java:6325)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.Component.createHierarchyEvents(Component.java:5555)
	at java.awt.Container.createHierarchyEvents(Container.java:1448)
	at java.awt.Component.show(Component.java:1639)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at javax.swing.JComponent.setVisible(JComponent.java:2644)
	at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:394)
	at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270)
	at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132)
	at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67)
	at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616)
	at javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591)
	at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647)
	at javax.swing.plaf.synth.SynthTabbedPaneUI$1.mousePressed(SynthTabbedPaneUI.java:312)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
**Platform information:**
 - OS: Linux
 - Version 2.100

**Additional context**
Could be caused by wrong configuration

**Comment by wsbrenk** [comment]
Dublicate of #396

**Comment by akasolace** [comment]
@heteroping this bug should be fixed in 3.0 branch. Can you please check it is the case for you, thank you
