### ISSUE TITLE
[eBUG] DBUpdate exception (no new columns for playernames)

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#455]
java.lang.NullPointerException
	at core.model.player.Player.getAgeWithDaysAsString(Player.java:613)
	at core.model.player.Player.getAgeWithDaysAsString(Player.java:608)
	at core.model.player.Player.getAlterWithAgeDaysAsString(Player.java:604)
	at core.gui.model.UserColumnFactory$26.getTableEntry(UserColumnFactory.java:738)
	at core.gui.model.PlayerOverviewModel.initData(PlayerOverviewModel.java:163)
	at core.gui.model.PlayerOverviewModel.setValues(PlayerOverviewModel.java:89)
	at module.playerOverview.PlayerOverviewTable.initModel(PlayerOverviewTable.java:144)
	at module.playerOverview.PlayerOverviewTable.<init>(PlayerOverviewTable.java:33)
	at module.playerOverview.SpielerUebersichtsPanel.initSpielerTabelle(SpielerUebersichtsPanel.java:186)
	at module.playerOverview.SpielerUebersichtsPanel.initComponents(SpielerUebersichtsPanel.java:118)
	at module.playerOverview.SpielerUebersichtsPanel.<init>(SpielerUebersichtsPanel.java:43)
	at module.playerOverview.PlayerOverviewModule.createTabPanel(PlayerOverviewModule.java:30)
	at core.gui.comp.tabbedPane.HOTabbedPane.showTab(HOTabbedPane.java:38)
	at core.gui.HOMainFrame.initComponents(HOMainFrame.java:500)
	at core.gui.HOMainFrame.<init>(HOMainFrame.java:190)
	at core.gui.HOMainFrame.instance(HOMainFrame.java:284)
	at core.HO$1.run(HO.java:225)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Screenshots**

**Platform information:**
 - OS: [Windows / macOS / Linux]
 - Version (including build number)

**Additional context**

**Comment by akasolace** [comment]
@wsbrenk are you sure this has something to do with my change on the DB ?

**Comment by wsbrenk** [comment]
@akasolace your db changes were not carried out because an exception was thrown by my changes. the missing player table columns then were the reason for the npe.

**Comment by akasolace** [comment]
closed by #456
