### ISSUE TITLE
[BUG] NPE when selecting a player in the Lineup tab on brand new setup

### ISSUE THREAD

**Issue by tychobrailleur** [akasolace/HO#516]
**Describe the bug**
An NPE is raised when clicking on the dropdown menu for players in the Lineup tab when starting HO with a brand new database, after the first download.

The same problem arises when selecting a player in the Squad tab.

```
java.lang.NullPointerException
	at module.playerOverview.SpielerDetailPanel.setLabels(SpielerDetailPanel.java:368)
	at module.playerOverview.SpielerDetailPanel.setSpieler(SpielerDetailPanel.java:275)
	at module.playerOverview.SpielerUebersichtsPanel.setPlayer(SpielerUebersichtsPanel.java:56)
	at core.gui.HOMainFrame.setActualSpieler(HOMainFrame.java:292)
	at module.playerOverview.SpielerUebersichtsPanel.lambda$addTableSelectionListeners$2(SpielerUebersichtsPanel.java:261)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at javax.swing.JTable.setRowSelectionInterval(JTable.java:2166)
	at module.playerOverview.SpielerUebersichtNamenTable.setSpieler(SpielerUebersichtNamenTable.java:45)
	at module.playerOverview.SpielerUebersichtsPanel.setPlayer(SpielerUebersichtsPanel.java:54)
	at core.gui.HOMainFrame.setActualSpieler(HOMainFrame.java:292)
	at module.lineup.LineupPanel$1.synchronizeSelection(LineupPanel.java:265)
	at module.lineup.LineupPanel$1.valueChanged(LineupPanel.java:242)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at javax.swing.JTable.setRowSelectionInterval(JTable.java:2166)
	at module.lineup.LineupPanel$1.synchronizeSelection(LineupPanel.java:261)
	at module.lineup.LineupPanel$1.valueChanged(LineupPanel.java:244)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at javax.swing.JTable.setRowSelectionInterval(JTable.java:2166)
	at module.playerOverview.SpielerUebersichtNamenTable.setSpieler(SpielerUebersichtNamenTable.java:45)
	at module.lineup.LineupPanel.setPlayer(LineupPanel.java:63)
	at core.gui.HOMainFrame.setActualSpieler(HOMainFrame.java:291)
	at module.lineup.PlayerPositionPanel.focusGained(PlayerPositionPanel.java:136)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:220)
	at java.awt.Component.processFocusEvent(Component.java:6424)
	at java.awt.Component.processEvent(Component.java:6291)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:986)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:610)
	at java.awt.Component.dispatchEventImpl(Component.java:4762)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

After closing the initial NPE error dialog, multiple other ones appear, which is probably one per player.

**To Reproduce**
1. Start with a brand installation of HO from master
2. Download data from HT
3. Go to the Lineup tab
4. Click on the dropdown of a player to select a different one.

**Screenshots**
![Screenshot 2020-05-14 at 19 04 06](https://user-images.githubusercontent.com/114285/81969340-b5650e80-9615-11ea-8e6f-1cc846399cc7.png)

**Platform information:**
 - OS: macOS
 - Version HEAD of master branch

**Additional context**
N/A

**Comment by tychobrailleur** [comment]
In `SpielerDetailPanel`, `info` is null:

```
        if (m_clPlayer.getLastMatchRating() > 0) {
            m_jpLastMatchRating.setYellowStar(true);
            MatchKurzInfo info = DBManager.instance().getMatchesKurzInfoByMatchID(m_clPlayer.getLastMatchId());
            m_jpLastMatchRating.setRating((float)m_clPlayer.getLastMatchRating());
            m_jpLastMatchRating.setMatchInfo(m_clPlayer.getLastMatchDate(), info.getMatchTyp());
            m_jpLastMatchRating.getLabelMatch();
        }
```

At that point there isn't any match in the db:

```
select count(*) from Matcheskurzinfo
0
```

**Comment by tychobrailleur** [comment]
I don't understand why matches were not downloaded on the first download.  Doing a download again solves the problem.

So two things to address:
- Handle the null check in `SpielerDetailPanel`
- Find the root cause as to why the first download doesn't download matches.

**Comment by akasolace** [comment]
According to @steffanots this issue also exist in 3.0 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akasolace** [comment]
At least the issue on lineup tab 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tychobrailleur** [comment]
> According to @steffanots this issue also exist in 3.0

Ok, that's quite likely.

Looking into this, the first time we download everything, team id is still set to 0, so downloads in `DownloadDialog#startDownload` are not happening.  The second time, team id is set, all good.

**Comment by tychobrailleur** [comment]
> Looking into this, the first time we download everything, team id is still set to 0, so downloads in `DownloadDialog#startDownload` are not happening. The second time, team id is set, all good.

It seems to be a known “behaviour”: 
cf. https://github.com/akasolace/HO/blob/master/src/main/java/core/net/DownloadDialog.java#L279

So as I mentioned above, we at least need to add a null check, but I am wondering if we should also address that issue.

**Comment by akasolace** [comment]
looking the blame this comment has been there for ever ... can't think of a reason why it behaves like this ...

**Comment by tychobrailleur** [comment]
It suggests it's something to do with training... I have swapped downloading the HRF details and match download, and this fixes the problem.  This may have unintended consequences so let's keep an eye on this, but with a brand new db it works great – great thing is that League Details are also populated without having to download again.

**Comment by steffanots** [comment]
> Handle the null check in SpielerDetailPanel
I can add a check anyway. 
I wonder how this would behave on the player we buy!? I'll buy a player soon so I'll try. There will probably be a bug. :)
I can add a check anyway.

**Comment by tychobrailleur** [comment]
> > Handle the null check in SpielerDetailPanel
> 
> I can add a check anyway.

I have already added one in the PR: https://github.com/akasolace/HO/pull/517

> I wonder how this would behave on the player we buy!? I'll buy a player soon so I'll try. There will probably be a bug.
> I can add a check anyway. :)

It'd be worth checking how this behaves.
