### ISSUE TITLE
[BUG] NullPointerException when clearling lineup

### ISSUE THREAD

**Issue by DSwissK** [akasolace/HO#573]
**Describe the bug**

**To Reproduce**
1. Go to 'Lineup'
2. Click on 'Clear Lineup' (red button bottom right)
3. See error :
java.lang.NullPointerException
	at module.lineup.Lineup.UpdateLineupWithMatchOrder(Lineup.java:2013)
	at core.rating.RatingPredictionManager.setLineupEvolution(RatingPredictionManager.java:191)
	at core.rating.RatingPredictionManager.<init>(RatingPredictionManager.java:114)
	at core.rating.RatingPredictionManager.<init>(RatingPredictionManager.java:119)
	at module.lineup.Lineup.setRatings(Lineup.java:550)
	at core.model.HOModel.getLineup(HOModel.java:139)
	at module.lineup.AufstellungsDetailPanel.setLabels(AufstellungsDetailPanel.java:252)
	at module.lineup.AufstellungsDetailPanel.refresh(AufstellungsDetailPanel.java:585)
	at module.lineup.LineupPanel.update(LineupPanel.java:133)
	at module.lineup.AufstellungsAssistentPanel.actionPerformed(AufstellungsAssistentPanel.java:246)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Screenshots**
https://imgur.com/a/oRmSkOq

**Platform information:**
 - OS: Windows 
 - Version 3.000

**Additional info**
Same error happens then when I'm click on any clear positional orders or clear reserve bank. Also, when I start assistant and click green OK.

**Comment by akasolace** [comment]
hi @DSwissK , are you still experiencing the issue?
could you please attached a copy of your db folder to the ticket.
Thank you

**Comment by timeout972** [comment]
Bonjour,

same problems

Platform information:
OS: Macos 10.13 and Macos 10.15
Version 3.000

[database.log](https://github.com/akasolace/HO/files/4795052/database.log)

**Comment by akasolace** [comment]
@timeout972  could you share your db please ?

**Comment by timeout972** [comment]
Bonjour,
[db copie.zip](https://github.com/akasolace/HO/files/4806306/db.copie.zip)

**Comment by timeout972** [comment]
Bonjour,

After updating my database everything works again!!!
Thank you for this work
