### ISSUE TITLE
java.lang.NoClassDefFoundError: okhttp3/OkHttpClient$Builder

### ISSUE THREAD

**Issue by CesIAapprentice** [akasolace/HO#589]
Machine : Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
Installer : https://github.com/akasolace/HO/releases/download/3.0/HO-3.0.2.2728.deb

Hi, I get this error when clicking on 'League details' (or so, I've got it in Spanish) :

java.lang.NoClassDefFoundError: okhttp3/OkHttpClient$Builder
	at module.series.promotion.HttpDataSubmitter.initializeHttpsClient(HttpDataSubmitter.java:263)
	at module.series.promotion.HttpDataSubmitter.fetchSupportedLeagues(HttpDataSubmitter.java:45)
	at module.series.promotion.LeaguePromotionHandler.isActive(LeaguePromotionHandler.java:50)
	at module.series.promotion.PromotionInfoPanel.lambda$new$1(PromotionInfoPanel.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: okhttp3.OkHttpClient$Builder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 17 more

Thanx

**Comment by akasolace** [comment]
@tychobrailleur   @yaute74  could one of you take care of this one ?

**Comment by tychobrailleur** [comment]
Is that problem present with the `deb` package with the new 4.0 installer?

**Comment by tychobrailleur** [comment]
@yaute74 @akasolace I don't know if either of you can point me to the right direction: when I build the `deb` package locally and inspect the `data.tar.gz` in it, I see no dependency added to it.  Looking at the released `deb`, I do indeed see the deps, and I can also see that the okhttp dep is missing.

My expectation would be that all the gradle deps would be automatically copied in the package, but it doesn't seem to be the case.  Any idea where should I look?

**Comment by akasolace** [comment]
@tychobrailleur  @yaute74  first user to ever report this error so I am not sure we should bother to much actually ....

**Comment by akasolace** [comment]
@CesIAapprentice  can you confirm you are still experiencing this issue ?

**Comment by yaute74** [comment]
I am not on a debian linux distribution, but no error on my side with the last package

**Comment by tychobrailleur** [comment]
Checking the `deb` package from the release, okhttp jar is indeed missing, I have created a PR that copies project dependencies into the package for 3.x release.
