### ISSUE TITLE
[BUG] Evil Card

### ISSUE THREAD

**Issue by aristodemos2008** [akasolace/HO#626]
**Describe the bug**
I receive a java error when I open the Evil Card tab in HO 3.0. The tab remains empty after the error.

java.lang.NullPointerException
	at core.db.MatchHighlightsTable.getMatchHighlightsByTypIdAndPlayerId(MatchHighlightsTable.java:137)
	at core.db.DBManager.getMatchHighlightsByTypIdAndPlayerId(DBManager.java:1304)
	at module.evilcard.gui.PlayersTableModel.generateData(PlayersTableModel.java:236)
	at module.evilcard.gui.PlayersTableModel.refresh(PlayersTableModel.java:122)
	at module.evilcard.gui.PlayersPanel.initComponents(PlayersPanel.java:92)
	at module.evilcard.gui.PlayersPanel.<init>(PlayersPanel.java:29)
	at module.evilcard.gui.EvilCardPanel.initComponents(EvilCardPanel.java:32)
	at module.evilcard.gui.EvilCardPanel.initialize(EvilCardPanel.java:19)
	at core.gui.comp.panel.LazyPanel.callInitialize(LazyPanel.java:150)
	at core.gui.comp.panel.LazyPanel.access$300(LazyPanel.java:16)
	at core.gui.comp.panel.LazyPanel$2.hierarchyChanged(LazyPanel.java:137)
	at java.awt.Component.processHierarchyEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.Component.addNotify(Unknown Source)
	at java.awt.Container.addNotify(Unknown Source)
	at javax.swing.JComponent.addNotify(Unknown Source)
	at java.awt.Container.addImpl(Unknown Source)
	at javax.swing.JTabbedPane.insertTab(Unknown Source)
	at javax.swing.JTabbedPane.addTab(Unknown Source)
	at core.gui.comp.tabbedPane.HOTabbedPane.addTab(HOTabbedPane.java:22)
	at core.gui.comp.tabbedPane.HOTabbedPane.showTab(HOTabbedPane.java:38)
	at core.gui.HOMainFrame$2.actionPerformed(HOMainFrame.java:584)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**To Reproduce**
1. Press Ctrl+4.

**Screenshots**
[error](https://www.screencast.com/t/iygeHS51u3F)

**Platform information:**
 - OS: Windows
 - Version 10.0.18362.900
- Java 1.8.0_202-b08

**Comment by tychobrailleur** [comment]
Thanks @aristodemos2008! This bug was previously reported (#505), and this feature will be removed in 4.0.  I am going to close this.
