### ISSUE TITLE
[BUG] Click on Reset Formation

### ISSUE THREAD

**Issue by rivoluzione** [akasolace/HO#642]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Platform information:**
 - OS: [Windows / macOS / Linux]
 - Version (including build number)

**Additional context**
java.lang.NullPointerException
	at module.lineup.Lineup.UpdateLineupWithMatchOrder(Lineup.java:2014)
	at core.rating.RatingPredictionManager.setLineupEvolution(RatingPredictionManager.java:191)
	at core.rating.RatingPredictionManager.<init>(RatingPredictionManager.java:114)
	at core.rating.RatingPredictionManager.<init>(RatingPredictionManager.java:119)
	at module.lineup.Lineup.setRatings(Lineup.java:550)
	at core.model.HOModel.getLineup(HOModel.java:139)
	at module.lineup.AufstellungsDetailPanel.setLabels(AufstellungsDetailPanel.java:252)
	at module.lineup.AufstellungsDetailPanel.refresh(AufstellungsDetailPanel.java:585)
	at module.lineup.LineupPanel.update(LineupPanel.java:133)
	at module.lineup.AufstellungsAssistentPanel.actionPerformed(AufstellungsAssistentPanel.java:246)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by akasolace** [comment]
@rivoluzione can you give more information ?  This is happening when reseting lineup? Is it the first time it happened ? Is there anythig specific with this lineup you are aware of ?

**Comment by akasolace** [comment]
/remind me to close issue if no update in 1 week

**Comment by wsbrenk** [comment]
same as #573: Exception when clean a lineup with new behaviour #603

**Comment by akasolace** [comment]
@rivoluzione it should have been fixed in 4.0
