### ISSUE TITLE
[BUG] corrupted db on dev 4.0.0.3116

### ISSUE THREAD

**Issue by DavidatorusF** [akasolace/HO#686]
**Describe the bug**
using db from stable 3.0 on fresh dev install give me this error:

java.lang.NullPointerException
at module.lineup.AufstellungsAssistentPanel.initComponents(AufstellungsAssistentPanel.java:555)
at module.lineup.AufstellungsAssistentPanel.<⁠init>(AufstellungsAssistentPanel.java:115)
at module.lineup.LineupPanel.initComponents(LineupPanel.java:164)
at module.lineup.LineupPanel.<⁠init>(LineupPanel.java:52)
at module.lineup.LineupMasterView.initComponents(LineupMasterView.java:52)
at module.lineup.LineupMasterView.<⁠init>(LineupMasterView.java:40)
at module.lineup.LineupModule.createTabPanel(LineupModule.java:29)
at core.gui.comp.tabbedPane.HOTabbedPane.showTab(HOTabbedPane.java:38)
at core.gui.HOMainFrame.initComponents(HOMainFrame.java:464)
at core.gui.HOMainFrame.<⁠init>(HOMainFrame.java:168)
at core.gui.HOMainFrame.instance(HOMainFrame.java:249)
at core.HO.lambda$main$0(HO.java:204)
at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

my db : https://we.tl/t-gHvEq3VZms

**Platform information:**
 - OS: [Linux] Ubuntu 16.04

**Comment by akasolace** [comment]
@DavidatorusF I just tried with latest HO! r3122 and I don't see any pbs. Can you please confirm it is also the case for you....

**Comment by DavidatorusF** [comment]
@akasolace no problem on HO 3... the problem is on dev HO 4

**Comment by akasolace** [comment]
@DavidatorusF je parle de la derniere version de HO 4.0.0.3122

**Comment by DavidatorusF** [comment]
oh... ok

nice job ^^

well done... thread can be closed
