### ISSUE TITLE
[BUG] HO-4.0.1.3242-portable-win-BETA nullpointer with 2nd-team

### ISSUE THREAD

**Issue by Volker-brdb** [akasolace/HO#710]
**Describe the bug**
HO4 will not start with a 2nd-team and an database for the 2nd-team from HO3
For the 1st team everything works even with a DB from HO3

**To Reproduce**
1. start ho.exe
2. create second user via File>Database>Database/User administration
3. quit HO4
4. copy db-files from HO3 2nd-team db-folder to db-folder of HO4 2nd-team
5. start ho.exe
6. choose 2nd-team in startup/login-screen
7. nullpointer execption appears.....nothing else possible than killing ho.exe via task-manger

**Screenshots**
![image](https://user-images.githubusercontent.com/72230479/94960068-81ba5080-04f2-11eb-8637-70ac81e32a19.png)

java.lang.NullPointerException
	at core.gui.theme.ImageUtilities.getCountryFlagIcon(ImageUtilities.java:446)
	at core.gui.model.UserColumnFactory$25.getTableEntry(UserColumnFactory.java:573)
	at core.gui.model.PlayerOverviewModel.initData(PlayerOverviewModel.java:164)
	at core.gui.model.PlayerOverviewModel.setValues(PlayerOverviewModel.java:92)
	at module.playerOverview.PlayerOverviewTable.initModel(PlayerOverviewTable.java:162)
	at module.playerOverview.PlayerOverviewTable.<init>(PlayerOverviewTable.java:39)
	at module.playerOverview.SpielerUebersichtsPanel.initSpielerTabelle(SpielerUebersichtsPanel.java:174)
	at module.playerOverview.SpielerUebersichtsPanel.initComponents(SpielerUebersichtsPanel.java:106)
	at module.playerOverview.SpielerUebersichtsPanel.<init>(SpielerUebersichtsPanel.java:34)
	at module.playerOverview.PlayerOverviewModule.createTabPanel(PlayerOverviewModule.java:30)
	at core.gui.comp.tabbedPane.HOTabbedPane.showTab(HOTabbedPane.java:38)
	at core.gui.HOMainFrame.initComponents(HOMainFrame.java:464)
	at core.gui.HOMainFrame.<init>(HOMainFrame.java:168)
	at core.gui.HOMainFrame.instance(HOMainFrame.java:249)
	at core.HO.lambda$main$0(HO.java:202)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Platform information:**
 - OS: Windows
 - Version : HO-4.0.1.3242-portable-win-BETA

**Additional context**
here are the logs
[HO-2020-10-02.log](https://github.com/akasolace/HO/files/5319843/HO-2020-10-02.log)
[output.log](https://github.com/akasolace/HO/files/5319844/output.log)
[error.log](https://github.com/akasolace/HO/files/5319845/error.log)

**Comment by akasolace** [comment]
@Volker-brdb hello, could you please share a zip of your db ...

**Comment by Volker-brdb** [comment]
@akasolace sure, here is the zip
[db2.zip](https://github.com/akasolace/HO/files/5319967/db2.zip)

**Comment by wsbrenk** [comment]
Gaspar Marquez has countryId 190
