### ISSUE TITLE
[BUG] java.lang.NullPointerException 	at module.lineup.Lineup.UpdateLineupWithMatchOrder(Lineup.java:2013)

### ISSUE THREAD

**Issue by pc-partner** [akasolace/HO#761]
When resetting the orders for the game (red icon, right bottom screen) we get this error:
It worked before for months:

java.lang.NullPointerException
	at module.lineup.Lineup.UpdateLineupWithMatchOrder(Lineup.java:2013)
	at core.rating.RatingPredictionManager.setLineupEvolution(RatingPredictionManager.java:191)
	at core.rating.RatingPredictionManager.<init>(RatingPredictionManager.java:114)
	at core.rating.RatingPredictionManager.<init>(RatingPredictionManager.java:119)
	at module.lineup.Lineup.setRatings(Lineup.java:550)
	at core.model.HOModel.getLineup(HOModel.java:139)
	at module.lineup.AufstellungsDetailPanel.setLabels(AufstellungsDetailPanel.java:252)
	at module.lineup.AufstellungsDetailPanel.refresh(AufstellungsDetailPanel.java:585)
	at module.lineup.LineupPanel.update(LineupPanel.java:133)
	at module.lineup.AufstellungsAssistentPanel.actionPerformed(AufstellungsAssistentPanel.java:246)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by akasolace** [comment]
@pc-partner which version of HO are you using? Could you share the problematic database in this post ?

**Comment by pc-partner** [comment]
3.000

[db_singleUser-2020-10-30.zip](https://github.com/akasolace/HO/files/5463601/db_singleUser-2020-10-30.zip)

**Comment by akasolace** [comment]
Because we are so closed from 4.0 release. Could you check if the error still occur with latest beta vesion? For safety please keep a backup of your existing db before upgrading it. 
If the error still there, please edit your first post: remove the logs or keep only the first 2 lines and give the exact steps that throws the error.
Thank you

**Comment by pc-partner** [comment]
That is the fix...now running 4.0
DOwnload the zip file and copy the files into existing folder.

**Comment by akasolace** [comment]
ok so just to be sure, you are saying it works with 4.0 ? I can close this ticket ?

**Comment by pc-partner** [comment]
Correct
