### ISSUE TITLE
New man marking[BUG]

### ISSUE THREAD

**Issue by pc-partner** [akasolace/HO#776]
**Describe the bug**
When clicking on the botton "new man marking" I get the following java error.
Version 4 r 3276
![2020-11-08_14-03-32](https://user-images.githubusercontent.com/19971929/98465749-631f3780-21cb-11eb-97ce-7db156970ef6.png)

java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at module.teamAnalyzer.vo.PlayerInfo.<init>(PlayerInfo.java:51)
	at module.teamAnalyzer.ht.HattrickManager.downloadPlayers(HattrickManager.java:111)
	at module.lineup.substitution.SubstitutionDataProvider.getOpponentPlayers(SubstitutionDataProvider.java:139)
	at module.lineup.substitution.SubstitutionEditView.<init>(SubstitutionEditView.java:96)
	at module.lineup.substitution.SubstitutionEditDialog.initComponents(SubstitutionEditDialog.java:89)
	at module.lineup.substitution.SubstitutionEditDialog.initDialog(SubstitutionEditDialog.java:58)
	at module.lineup.substitution.SubstitutionEditDialog.<init>(SubstitutionEditDialog.java:42)
	at module.lineup.substitution.SubstitutionOverview.getSubstitutionEditDialog(SubstitutionOverview.java:311)
	at module.lineup.substitution.SubstitutionOverview.doNewOrder(SubstitutionOverview.java:287)
	at module.lineup.substitution.SubstitutionOverview$ManMarkingAction.actionPerformed(SubstitutionOverview.java:592)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by wsbrenk** [comment]
@pc-partner i'm a little bit confused concerning the HO version you mention. The latest beta i know is r3269 from last weekend. In this version the bug should be fixed ( see #743). Could you try to verify that?

**Comment by pc-partner** [comment]
Hi, see pictures.
This is the one I downloaded after I logged an other case with another bug. Do I need to downgrade?
![2020-11-08_17-04-22](https://user-images.githubusercontent.com/19971929/98470213-830f2500-21e4-11eb-9dd1-1d1616690da9.png)

**Comment by akasolace** [comment]
@pc-partner I will release a new version shortly. For the time being you should stick with your version. In the future I suggest you stick on BETA or STABLE channel. DEV channel is really intended for devs only.

**Comment by wsbrenk** [comment]
@akasolace do you know if DEV r3276 is older than BETA r3269?

**Comment by akasolace** [comment]
yes I think it is. When I was debugging the updater tool, I pushed a lot of dev version. Once I merged one of your branch with a lower version numbers. I did not bother to fix it once I realized because I thought only the 2 of us where using dev release.

**Comment by pc-partner** [comment]
Sry guys. My bad

**Comment by akasolace** [comment]
I close the issue then.  I might release a new dev version later today that you can upgrade to. After that you can put beta channel in your preferences
