### ISSUE TITLE
[BUG] HO 4.1 not starting....start process hangs at step Load XtraDaten

### ISSUE THREAD

**Issue by Volker-brdb** [akasolace/HO#834]
**Describe the bug**
HO 4.1 not starting....start process hangs at step Load XtraDaten

**To Reproduce**
- Start HO 4.1
- kill via TaskManager
- start HO 4.1 again

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/72230479/102719698-bcf93e00-42ef-11eb-8cf9-25644ce800f5.JPG)

**Platform information:**
 - OS: Windows
 - Version HOSetup-4.1.3310.2 and HO-4.1.3310.2-portable-win

  
**Additional context**
---

**Comment by wsbrenk** [comment]
it is not a good idea to kill HO via TaskManager - you need to restore one of your previous database backups to start successfully again.

**Comment by Volker-brdb** [comment]
It has never started successfully. This occurs since I installed it the first time. 
Even putting a db-folder and a user.json into the ho-folder doesn't help

**Comment by wsbrenk** [comment]
could you check if there is an error message logged in the log file in the folder %APPDATA%/HO/logs?

**Comment by Volker-brdb** [comment]
Yes....

**output.log**
 [Info]    HO: VERSION: 4.1   versionType:  RELEASE   RevisionNumber: 3310


**error.log**
Dez. 21, 2020 9:38:01 AM org.hsqldb.persist.Logger logInfoEvent
INFORMATION: dataFileCache open start
Dez. 21, 2020 9:38:01 AM org.hsqldb.persist.Logger logInfoEvent
INFORMATION: dataFileCache open end
java.lang.ArrayIndexOutOfBoundsException: Index 49 out of bounds for length 49
	at core.db.UserColumnsTable.loadModel(UserColumnsTable.java:130)
	at core.db.DBManager.loadHOColumModel(DBManager.java:1680)
	at core.gui.model.UserColumnController.load(UserColumnController.java:63)
	at core.HO.main(HO.java:184)
	at core.HOLauncher.main(HOLauncher.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Uncaught error fetching image:
java.lang.NullPointerException
	at java.desktop/sun.awt.image.URLImageSource.getConnection(URLImageSource.java:101)
	at java.desktop/sun.awt.image.URLImageSource.getDecoder(URLImageSource.java:111)
	at java.desktop/sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:263)
	at java.desktop/sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:212)
	at java.desktop/sun.awt.image.ImageFetcher.run(ImageFetcher.java:176)

**Comment by wsbrenk** [comment]
@tychobrailleur @akasolace: looks like it's dealing with this #611

**Comment by wsbrenk** [comment]
https://github.com/akasolace/HO/commit/7b681fa0d62837e494478197f1819e6f68b69a62 should fix the ArrayIndexOutOfBoundsException, but i have no idea what risks and side effects this has and if this would fix this issue completly.

**Comment by akasolace** [comment]
@wsbrenk It has been reported only once, I am not sure what we can do here .... I think we can just close this issue, what do you think ?

**Comment by wsbrenk** [comment]
i think it should be fix by https://github.com/akasolace/HO/commit/7b681fa0d62837e494478197f1819e6f68b69a62
