### ISSUE TITLE
[BUG] java error expanding download filter

### ISSUE THREAD

**Issue by aristodemos2008** [akasolace/HO#909]
**Describe the bug**
I get a java error when I expand the tree in the download filter

**To Reproduce**
1. Press F11
2. Expand "current matches"
3. Expand "integrated matches"
4. Mouse hover the download window

**Screenshots**
[java error](https://www.screencast.com/t/VXsjAHpAIou) 

**Platform information:**
 - OS: Windows
 - Version HO-4.1.3310.2-portable-win-JRE

**Additional context**
```
java.lang.NullPointerException
	at java.desktop/javax.swing.RepaintManager.getVolatileOffscreenBuffer(RepaintManager.java:1075)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1543)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1060)
	at com.github.weisj.darklaf.ui.cell.hint.CellHintPopupListener$PopupComponent.paint(CellHintPopupListener.java:379)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5262)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1618)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1060)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:75)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:112)
	at java.desktop/java.awt.Container.paint(Container.java:2002)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:876)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1884)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at java.desktop/java.awt.Component.show(Component.java:1717)
	at java.desktop/java.awt.Component.setVisible(Component.java:1664)
	at java.desktop/java.awt.Window.setVisible(Window.java:1023)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at core.net.DownloadDialog.initComponents(DownloadDialog.java:246)
	at core.net.DownloadDialog.<init>(DownloadDialog.java:80)
	at core.gui.HOMainFrame.actionPerformed(HOMainFrame.java:326)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:349)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:975)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2900)
	at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699)
	at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at java.desktop/javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677)
	at java.desktop/javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:311)
	at java.desktop/javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:297)
	at java.desktop/javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2993)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2985)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2862)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4893)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by tychobrailleur** [comment]
This seems to happen with a darklaf theme when the whole checkbox node `CheckedNode` in the `CheckBoxTree` is not fully visible in the panel, and it tries to render the "hint popup" (i.e. a tooltip displaying the full text above the component).  Scrolling the panel sideways exhibits the same issue on the entries that are cutoff on the left at the top.

(There is a similar issue reported for JMeter:
https://stackoverflow.com/questions/65827396/jmeter-5-4-java-lang-nullpointerexception-in-thread-threadawt-eventqueue-0-6)

**Comment by tychobrailleur** [comment]
NPE occurs when `CellHintPopupListener` tries to retrieve `CheckBoxTree` parent as it renders the popup component, it doesn't seem to be set correct as it is `null`.

Probably not related but the following warning also appears:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.github.weisj.darklaf.ui.DarkPopupFactory (file:/home/sebastien/.gradle/caches/modules-2/files-2.1/com.github.weisj/darklaf-core/2.5.5/8a609c3473a1e191e06de38f9eaf06caefca6682/darklaf-core-2.5.5.jar) to method javax.swing.JRootPane.setUseTrueDoubleBuffering(boolean)
WARNING: Please consider reporting this to the maintainers of com.github.weisj.darklaf.ui.DarkPopupFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by tychobrailleur** [comment]
`com.github.weisj.darklaf.ui.tree.DarkTreeUI` creates the popup listener when the component is being created, when the tree has not been added to a container yet, and therefore has no parent.  Not sure why the reference doesn't get the parent later, it could be the tree is a copy of the actual component.  Still digging.

**Comment by akasolace** [comment]
@tychobrailleur great that you have been already looking into it. So if I understand correctly it is a Darklaf issue and it works as expected under Nimbus, correct?

**Comment by tychobrailleur** [comment]
> @tychobrailleur great that you have been already looking into it. So if I understand correctly it is a Darklaf issue and it works as expected under Nimbus, correct?

Yes.  I haven't figured out yet if this was due to some funky logic on our side in `CheckBoxTree`, I'll see if I can recreate a smaller repro to isolate.

**Comment by tychobrailleur** [comment]
I have a [small repro](https://gist.github.com/tychobrailleur/8bc41e4adc930a2aad1f4ed159df369d) of the issue with darklaf, the issue occurs when a custom `TreeCellRenderer` is used.  I will submit a bug report to the darklaf project.

In the meantime I found a far from perfect workaround which prevents the NPE, but does not fully show the expected text, I'll submit a PR.

**Comment by weisJ** [comment]
> Probably not related but the following warning also appears:
> 
> ```
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.github.weisj.darklaf.ui.DarkPopupFactory (file:/home/sebastien/.gradle/caches/modules-2/files-2.1/com.github.weisj/darklaf-core/2.5.5/8a609c3473a1e191e06de38f9eaf06caefca6682/darklaf-core-2.5.5.jar) to method javax.swing.JRootPane.setUseTrueDoubleBuffering(boolean)
> WARNING: Please consider reporting this to the maintainers of com.github.weisj.darklaf.ui.DarkPopupFactory
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> ```

To give some context about this warning. The warning is due to an transparency issue with the X11 window implementation of the jdk. Heavyweight popups disable double-buffering, which results in forced opaque windows on some desktop managers (e.g. Gnome).

**Comment by akasolace** [comment]
@weisJ see you fixed it already, this is great !   Any ETA for v2.5.6 ?

**Comment by tychobrailleur** [comment]
> > Probably not related but the following warning also appears:
> > ```
> > WARNING: An illegal reflective access operation has occurred
> > WARNING: Illegal reflective access by com.github.weisj.darklaf.ui.DarkPopupFactory (file:/home/sebastien/.gradle/caches/modules-2/files-2.1/com.github.weisj/darklaf-core/2.5.5/8a609c3473a1e191e06de38f9eaf06caefca6682/darklaf-core-2.5.5.jar) to method javax.swing.JRootPane.setUseTrueDoubleBuffering(boolean)
> > WARNING: Please consider reporting this to the maintainers of com.github.weisj.darklaf.ui.DarkPopupFactory
> > WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> > WARNING: All illegal access operations will be denied in a future release
> > ```
> 
> To give some context about this warning. The warning is due to an transparency issue with the X11 window implementation of the jdk. Heavyweight popups disable double-buffering, which results in forced opaque windows on some desktop managers (e.g. Gnome).

Thanks for the context Jannis – I don't have any concern at this stage with these warnings, I just logged it in case it became relevant for my analysis.  

And thanks once again for the prompt help on this, truly appreciated.

**Comment by weisJ** [comment]
Sorry for the long delay regarding the the version. I was busy with by thesis the last few weeks and didn’t have much time. I still want to finish some last cleanup tasks before releasing the next version, but that should probably be done sometime next week, so I’ll be able to release the next version then.

**Comment by tychobrailleur** [comment]
No worries at all, thesis is far more important! Hope it is going well! 😉
I'll keep an eye out for the new release.

**Comment by akasolace** [comment]
Thanks for the update and all the best with the thesis !!

**Comment by tychobrailleur** [comment]
That would be my suggestion, yes.  It must have been released some time today, right? I checked this morning and it wasn't there.

**Comment by akasolace** [comment]
@tychobrailleur it is available now ...
